/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import CSSBeautify from "../../operations/CSSBeautify.mjs";
import CSSMinify from "../../operations/CSSMinify.mjs";
import CSSSelector from "../../operations/CSSSelector.mjs";
import FromMessagePack from "../../operations/FromMessagePack.mjs";
import GenericCodeBeautify from "../../operations/GenericCodeBeautify.mjs";
import JPathExpression from "../../operations/JPathExpression.mjs";
import JSONBeautify from "../../operations/JSONBeautify.mjs";
import JSONMinify from "../../operations/JSONMinify.mjs";
import JavaScriptBeautify from "../../operations/JavaScriptBeautify.mjs";
import JavaScriptMinify from "../../operations/JavaScriptMinify.mjs";
import JavaScriptParser from "../../operations/JavaScriptParser.mjs";
import Jsonata from "../../operations/Jsonata.mjs";
import RenderMarkdown from "../../operations/RenderMarkdown.mjs";
import SQLBeautify from "../../operations/SQLBeautify.mjs";
import SQLMinify from "../../operations/SQLMinify.mjs";
import SyntaxHighlighter from "../../operations/SyntaxHighlighter.mjs";
import ToCamelCase from "../../operations/ToCamelCase.mjs";
import ToKebabCase from "../../operations/ToKebabCase.mjs";
import ToMessagePack from "../../operations/ToMessagePack.mjs";
import ToSnakeCase from "../../operations/ToSnakeCase.mjs";
import XMLBeautify from "../../operations/XMLBeautify.mjs";
import XMLMinify from "../../operations/XMLMinify.mjs";
import XPathExpression from "../../operations/XPathExpression.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Code = {
    "CSS美化": CSSBeautify,
    "CSS压缩": CSSMinify,
    "CSS选择器": CSSSelector,
    "MessagePack解码": FromMessagePack,
    "通用代码美化": GenericCodeBeautify,
    "JPath表达式": JPathExpression,
    "JSON美化": JSONBeautify,
    "JSON压缩": JSONMinify,
    "JavaScript美化": JavaScriptBeautify,
    "JavaScript压缩": JavaScriptMinify,
    "JavaScript解析": JavaScriptParser,
    "Jsonata查询": Jsonata,
    "渲染Markdown": RenderMarkdown,
    "SQL美化": SQLBeautify,
    "SQL压缩": SQLMinify,
    "语法高亮": SyntaxHighlighter,
    "转换为Camel case": ToCamelCase,
    "转换为Kebab case": ToKebabCase,
    "MessagePack编码": ToMessagePack,
    "转换为Snake case": ToSnakeCase,
    "XML美化": XMLBeautify,
    "XML压缩": XMLMinify,
    "XPath表达式": XPathExpression,
};

export default OpModules;
