/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import Bzip2Compress from "../../operations/Bzip2Compress.mjs";
import Bzip2Decompress from "../../operations/Bzip2Decompress.mjs";
import Gunzip from "../../operations/Gunzip.mjs";
import Gzip from "../../operations/Gzip.mjs";
import LZ4Compress from "../../operations/LZ4Compress.mjs";
import LZ4Decompress from "../../operations/LZ4Decompress.mjs";
import LZMACompress from "../../operations/LZMACompress.mjs";
import LZMADecompress from "../../operations/LZMADecompress.mjs";
import LZNT1Decompress from "../../operations/LZNT1Decompress.mjs";
import LZStringCompress from "../../operations/LZStringCompress.mjs";
import LZStringDecompress from "../../operations/LZStringDecompress.mjs";
import RawDeflate from "../../operations/RawDeflate.mjs";
import RawInflate from "../../operations/RawInflate.mjs";
import Tar from "../../operations/Tar.mjs";
import Untar from "../../operations/Untar.mjs";
import Unzip from "../../operations/Unzip.mjs";
import Zip from "../../operations/Zip.mjs";
import ZlibDeflate from "../../operations/ZlibDeflate.mjs";
import ZlibInflate from "../../operations/ZlibInflate.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Compression = {
    "Bzip2压缩": Bzip2Compress,
    "Bzip2解压": Bzip2Decompress,
    "Gunzip": Gunzip,
    "Gzip": Gzip,
    "LZ4压缩": LZ4Compress,
    "LZ4解压": LZ4Decompress,
    "LZMA压缩": LZMACompress,
    "LZMA解压": LZMADecompress,
    "LZNT1解压": LZNT1Decompress,
    "LZString压缩": LZStringCompress,
    "LZString解压": LZStringDecompress,
    "Raw Deflate": RawDeflate,
    "Raw Inflate": RawInflate,
    "Tar": Tar,
    "Untar": Untar,
    "Unzip": Unzip,
    "Zip": Zip,
    "Zlib Deflate": ZlibDeflate,
    "Zlib Inflate": ZlibInflate,
};

export default OpModules;
