/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import Adler32Checksum from "../../operations/Adler32Checksum.mjs";
import AnalyseHash from "../../operations/AnalyseHash.mjs";
import AnalyseUUID from "../../operations/AnalyseUUID.mjs";
import Argon2 from "../../operations/Argon2.mjs";
import Argon2Compare from "../../operations/Argon2Compare.mjs";
import Bcrypt from "../../operations/Bcrypt.mjs";
import BcryptCompare from "../../operations/BcryptCompare.mjs";
import BcryptParse from "../../operations/BcryptParse.mjs";
import CMAC from "../../operations/CMAC.mjs";
import CTPH from "../../operations/CTPH.mjs";
import CipherSaber2Decrypt from "../../operations/CipherSaber2Decrypt.mjs";
import CipherSaber2Encrypt from "../../operations/CipherSaber2Encrypt.mjs";
import CompareCTPHHashes from "../../operations/CompareCTPHHashes.mjs";
import CompareSSDEEPHashes from "../../operations/CompareSSDEEPHashes.mjs";
import DeriveHKDFKey from "../../operations/DeriveHKDFKey.mjs";
import Fletcher16Checksum from "../../operations/Fletcher16Checksum.mjs";
import Fletcher32Checksum from "../../operations/Fletcher32Checksum.mjs";
import Fletcher64Checksum from "../../operations/Fletcher64Checksum.mjs";
import Fletcher8Checksum from "../../operations/Fletcher8Checksum.mjs";
import GenerateAllChecksums from "../../operations/GenerateAllChecksums.mjs";
import GenerateAllHashes from "../../operations/GenerateAllHashes.mjs";
import GenerateUUID from "../../operations/GenerateUUID.mjs";
import HAS160 from "../../operations/HAS160.mjs";
import HASSHClientFingerprint from "../../operations/HASSHClientFingerprint.mjs";
import HASSHServerFingerprint from "../../operations/HASSHServerFingerprint.mjs";
import HMAC from "../../operations/HMAC.mjs";
import JA3Fingerprint from "../../operations/JA3Fingerprint.mjs";
import JA3SFingerprint from "../../operations/JA3SFingerprint.mjs";
import JA4Fingerprint from "../../operations/JA4Fingerprint.mjs";
import JA4ServerFingerprint from "../../operations/JA4ServerFingerprint.mjs";
import JWTDecode from "../../operations/JWTDecode.mjs";
import JWTSign from "../../operations/JWTSign.mjs";
import JWTVerify from "../../operations/JWTVerify.mjs";
import Keccak from "../../operations/Keccak.mjs";
import LMHash from "../../operations/LMHash.mjs";
import LS47Decrypt from "../../operations/LS47Decrypt.mjs";
import LS47Encrypt from "../../operations/LS47Encrypt.mjs";
import MD2 from "../../operations/MD2.mjs";
import MD4 from "../../operations/MD4.mjs";
import MD5 from "../../operations/MD5.mjs";
import MD6 from "../../operations/MD6.mjs";
import NTHash from "../../operations/NTHash.mjs";
import RIPEMD from "../../operations/RIPEMD.mjs";
import SHA0 from "../../operations/SHA0.mjs";
import SHA1 from "../../operations/SHA1.mjs";
import SHA2 from "../../operations/SHA2.mjs";
import SHA3 from "../../operations/SHA3.mjs";
import SM2Decrypt from "../../operations/SM2Decrypt.mjs";
import SM2Encrypt from "../../operations/SM2Encrypt.mjs";
import SM3 from "../../operations/SM3.mjs";
import SSDEEP from "../../operations/SSDEEP.mjs";
import Scrypt from "../../operations/Scrypt.mjs";
import Shake from "../../operations/Shake.mjs";
import Snefru from "../../operations/Snefru.mjs";
import TCPIPChecksum from "../../operations/TCPIPChecksum.mjs";
import Whirlpool from "../../operations/Whirlpool.mjs";
import XORChecksum from "../../operations/XORChecksum.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Crypto = {
    "Adler-32校验和": Adler32Checksum,
    "哈希分析": AnalyseHash,
    "解析UUID": AnalyseUUID,
    "Argon2": Argon2,
    "Argon2比较": Argon2Compare,
    "Bcrypt": Bcrypt,
    "Bcrypt比较": BcryptCompare,
    "Bcrypt解析": BcryptParse,
    "CMAC": CMAC,
    "CTPH": CTPH,
    "CipherSaber2解密": CipherSaber2Decrypt,
    "CipherSaber2加密": CipherSaber2Encrypt,
    "比较CTPH哈希值": CompareCTPHHashes,
    "比较SSDEEP哈希值": CompareSSDEEPHashes,
    "派生HKDF密钥": DeriveHKDFKey,
    "Fletcher-16校验和": Fletcher16Checksum,
    "Fletcher-32校验和": Fletcher32Checksum,
    "Fletcher-64校验和": Fletcher64Checksum,
    "Fletcher-8校验和": Fletcher8Checksum,
    "生成所有校验和": GenerateAllChecksums,
    "哈希生成": GenerateAllHashes,
    "生成UUID": GenerateUUID,
    "HAS-160": HAS160,
    "HASSH客户端指纹": HASSHClientFingerprint,
    "HASSH服务器指纹": HASSHServerFingerprint,
    "HMAC": HMAC,
    "JA3指纹": JA3Fingerprint,
    "JA3S指纹": JA3SFingerprint,
    "JA4指纹": JA4Fingerprint,
    "JA4S指纹": JA4ServerFingerprint,
    "JWT解码": JWTDecode,
    "JWT签名": JWTSign,
    "JWT验证": JWTVerify,
    "Keccak": Keccak,
    "LM哈希": LMHash,
    "LS47解密": LS47Decrypt,
    "LS47加密": LS47Encrypt,
    "MD2": MD2,
    "MD4": MD4,
    "MD5": MD5,
    "MD6": MD6,
    "NT哈希": NTHash,
    "RIPEMD": RIPEMD,
    "SHA0": SHA0,
    "SHA1": SHA1,
    "SHA2": SHA2,
    "SHA3": SHA3,
    "SM2解密": SM2Decrypt,
    "SM2加密": SM2Encrypt,
    "SM3": SM3,
    "SSDEEP": SSDEEP,
    "Scrypt": Scrypt,
    "Shake": Shake,
    "Snefru": Snefru,
    "TCP/IP校验和": TCPIPChecksum,
    "Whirlpool": Whirlpool,
    "XOR校验和": XORChecksum,
};

export default OpModules;
