/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import AMFDecode from "../../operations/AMFDecode.mjs";
import AMFEncode from "../../operations/AMFEncode.mjs";
import CitrixCTX1Decode from "../../operations/CitrixCTX1Decode.mjs";
import CitrixCTX1Encode from "../../operations/CitrixCTX1Encode.mjs";
import DecodeText from "../../operations/DecodeText.mjs";
import EncodeText from "../../operations/EncodeText.mjs";
import FromHTMLEntity from "../../operations/FromHTMLEntity.mjs";
import FromPunycode from "../../operations/FromPunycode.mjs";
import NormaliseUnicode from "../../operations/NormaliseUnicode.mjs";
import RisonDecode from "../../operations/RisonDecode.mjs";
import RisonEncode from "../../operations/RisonEncode.mjs";
import TextEncodingBruteForce from "../../operations/TextEncodingBruteForce.mjs";
import ToHTMLEntity from "../../operations/ToHTMLEntity.mjs";
import ToPunycode from "../../operations/ToPunycode.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Encodings = {
    "AMF解码": AMFDecode,
    "AMF编码": AMFEncode,
    "Citrix CTX1解码": CitrixCTX1Decode,
    "Citrix CTX1编码": CitrixCTX1Encode,
    "文本解码": DecodeText,
    "文本编码": EncodeText,
    "HTML实体解码": FromHTMLEntity,
    "Punycode解码": FromPunycode,
    "Unicode正规化": NormaliseUnicode,
    "Rison解码": RisonDecode,
    "Rison编码": RisonEncode,
    "文本编码暴力破解": TextEncodingBruteForce,
    "HTML实体编码": ToHTMLEntity,
    "Punycode编码": ToPunycode,
};

export default OpModules;
