/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import Template from "../../operations/Template.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Handlebars = {
    "模板渲染": Template,
};

export default OpModules;
