/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import ProtobufDecode from "../../operations/ProtobufDecode.mjs";
import ProtobufEncode from "../../operations/ProtobufEncode.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Protobuf = {
    "Protobuf解码": ProtobufDecode,
    "Protobuf编码": ProtobufEncode,
};

export default OpModules;
