/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import HexToObjectIdentifier from "../../operations/HexToObjectIdentifier.mjs";
import HexToPEM from "../../operations/HexToPEM.mjs";
import JWKToPem from "../../operations/JWKToPem.mjs";
import ObjectIdentifierToHex from "../../operations/ObjectIdentifierToHex.mjs";
import PEMToJWK from "../../operations/PEMToJWK.mjs";
import ParseASN1HexString from "../../operations/ParseASN1HexString.mjs";
import ParseCSR from "../../operations/ParseCSR.mjs";
import ParseX509CRL from "../../operations/ParseX509CRL.mjs";
import ParseX509Certificate from "../../operations/ParseX509Certificate.mjs";
import PubKeyFromCert from "../../operations/PubKeyFromCert.mjs";
import PubKeyFromPrivKey from "../../operations/PubKeyFromPrivKey.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PublicKey = {
    "十六进制转OID": HexToObjectIdentifier,
    "十六进制转PEM": HexToPEM,
    "JWK转PEM": JWKToPem,
    "OID转十六进制": ObjectIdentifierToHex,
    "PEM转JWK": PEMToJWK,
    "解析ASN.1十六进制字符串": ParseASN1HexString,
    "解析CSR": ParseCSR,
    "解析X.509证书吊销列表": ParseX509CRL,
    "解析X.509证书": ParseX509Certificate,
    "从证书提取公钥": PubKeyFromCert,
    "从私钥提取公钥": PubKeyFromPrivKey,
};

export default OpModules;
