/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import ExtractDates from "../../operations/ExtractDates.mjs";
import ExtractDomains from "../../operations/ExtractDomains.mjs";
import ExtractEmailAddresses from "../../operations/ExtractEmailAddresses.mjs";
import ExtractFilePaths from "../../operations/ExtractFilePaths.mjs";
import ExtractHashes from "../../operations/ExtractHashes.mjs";
import ExtractIPAddresses from "../../operations/ExtractIPAddresses.mjs";
import ExtractMACAddresses from "../../operations/ExtractMACAddresses.mjs";
import ExtractURLs from "../../operations/ExtractURLs.mjs";
import Filter from "../../operations/Filter.mjs";
import FindReplace from "../../operations/FindReplace.mjs";
import Register from "../../operations/Register.mjs";
import RegularExpression from "../../operations/RegularExpression.mjs";
import Strings from "../../operations/Strings.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Regex = {
    "提取日期": ExtractDates,
    "提取域名": ExtractDomains,
    "提取Email地址": ExtractEmailAddresses,
    "提取文件路径": ExtractFilePaths,
    "提取哈希": ExtractHashes,
    "提取IP地址": ExtractIPAddresses,
    "提取MAC地址": ExtractMACAddresses,
    "提取URL": ExtractURLs,
    "过滤": Filter,
    "查找/替换": FindReplace,
    "Register": Register,
    "正则表达式": RegularExpression,
    "Strings": Strings,
};

export default OpModules;
