/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import ParseURI from "../../operations/ParseURI.mjs";
import URLDecode from "../../operations/URLDecode.mjs";
import URLEncode from "../../operations/URLEncode.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.URL = {
    "解析URI": ParseURI,
    "URL解码": URLDecode,
    "URL编码": URLEncode,
};

export default OpModules;
