const $=(id)=>document.getElementById(id);let last;const bridge=globalThis.pluginGuard;
function markdownText(value){return String(value??'').replace(/[\r\n\t]+/g,' ').replace(/\\/g,'\\\\').replace(/([`*_[\]<>#])/g,'\\$1')}
function markdownCode(value){return '`'+String(value??'').replace(/[\r\n\t]+/g,' ').replace(/`/g,'ˋ')+'`'}
function humanText(value){return String(value??'').replace(/\bFeature code\b/gi,'功能代码').replace(/\[redacted\]/gi,'[已脱敏]')}
const HUMAN_FINDING_CODES=Object.freeze({'dynamic-require':'动态依赖加载',eval:'动态代码执行','child-process':'子进程调用',shell:'命令解释器执行','whole-module-bridge':'整模块桥接暴露','remote-url':'远程网址','depth-limit':'目录深度超限','directory-race':'目录竞态风险',symlink:'符号链接','special-file':'特殊文件','case-collision':'路径大小写或 Unicode 冲突',manifest:'插件清单','manifest-field':'清单字段',entrypoint:'插件入口',categories:'分类配置',platform:'平台范围','feature-list':'功能列表','feature-code':'功能代码','feature-trigger':'功能触发器','manifest-json':'清单格式','manifest-read':'清单读取',containment:'路径越界','incomplete-file-read':'文件未完整读取','minified-preload':'预加载脚本可读性','relative-require-escape':'相对依赖越界','missing-relative-require':'相对依赖缺失','unknown-bridge':'未知桥接字段',secret:'疑似凭据','entry-invalidated':'入口已失效'});
function humanFindingCode(value){return HUMAN_FINDING_CODES[String(value??'')]||'未分类检查项'}
function humanFindingMessage(value,code){const text=humanText(value),raw=String(code??''),label=HUMAN_FINDING_CODES[raw];return label?text.split(raw).join(label):text}
function humanLevel(value){return({high:'高',medium:'中',low:'低'})[value]||humanText(value)}
function findingCounts(report){const shown=Number.isFinite(Number(report.retainedFindings))?Number(report.retainedFindings):(report.issues?.length||0)+(report.risks?.length||0),total=Number.isFinite(Number(report.findingTotals?.findings))?Number(report.findingTotals.findings):shown;return{shown,total,truncated:Boolean(report.findingsTruncated)||shown<total}}
function markdown(report){const counts=findingCounts(report),rows=['# 插件安全体检报告','','扫描时间：'+markdownText(report.scannedAt),'文件：'+Number(report.files||0)+'；字节：'+Number(report.bytes||0),'已展示发现：'+counts.shown+' / '+counts.total];if(counts.truncated)rows.push('','> 证据已截断；汇总数量覆盖完整扫描结果。');rows.push('','## 发现');for(const x of [...report.issues,...report.risks])rows.push('- '+markdownCode(humanLevel(x.level))+' '+markdownCode(humanFindingCode(x.code))+(x.file?' — '+markdownCode(humanText(x.file)):'')+'：'+markdownText(humanFindingMessage(x.message,x.code)));return rows.join('\n')}
async function copy(text,label){try{if(bridge?.copyText)await bridge.copyText(text);else await navigator.clipboard.writeText(text);$('status').textContent=label}catch{$('status').textContent='当前环境无法复制'}}
$('choose').addEventListener('click',async()=>{try{if(!bridge)throw new Error('插件安全体检桥接不可用。');await bridge.choosePluginDirectory();$('status').textContent='目录授权成功，尚未开始扫描。'}catch(e){$('status').textContent=e.message}});
$('scan').addEventListener('click',async()=>{try{if(!bridge)throw new Error('插件安全体检桥接不可用。');$('status').textContent='正在进行只读扫描…';last=await bridge.scan();$('map').textContent=last.manifest?`${humanText(last.manifest.name)} · 功能代码：${last.manifest.features.map(f=>humanText(f.code)).join(', ')||'无'}`:'没有有效清单';$('inventory').textContent=`${last.files} 个文件 · ${last.bytes.toLocaleString()} 字节`; $('risks').replaceChildren();for(const finding of [...last.issues,...last.risks]){const li=document.createElement('li');li.className=finding.level;li.textContent=`${humanLevel(finding.level)} ${humanFindingCode(finding.code)}${finding.file?' · '+humanText(finding.file):''}：${humanFindingMessage(finding.message,finding.code)}`;$('risks').append(li)}const counts=findingCounts(last);$('status').textContent=`只读扫描完成 · 已展示 ${counts.shown.toLocaleString()} / ${counts.total.toLocaleString()} 项发现${counts.truncated?'（证据已截断）':''}`}catch(e){$('status').textContent=humanText(e.message)}});
$('copyMarkdown').addEventListener('click',()=>last&&copy(markdown(last),'已复制脱敏后的 Markdown 报告'));
$('copyJson').addEventListener('click',()=>last&&copy(JSON.stringify(last,null,2),'已复制脱敏后的 JSON 报告'));
