const $=(id)=>document.getElementById(id);let plan,zipToken,destinationToken,filesToken;const bridge=globalThis.archiveWorkbench;
function render(next){plan=next;$('tree').replaceChildren();for(const entry of plan.entries){const li=document.createElement('li');li.textContent=`▣ ${entry.name} · ${entry.size.toLocaleString()} 字节`;$('tree').append(li)}$('summary').textContent=`共 ${plan.entries.length} 个条目，解压后 ${plan.total.toLocaleString()} 字节。遇到同名文件时默认重命名；预览未写入任何内容。`;}
function requireBridge(){if(!bridge)throw new Error('当前 ZTools 版本不支持压缩包能力桥。');}
$('chooseZip').addEventListener('click',async()=>{try{requireBridge();zipToken=await bridge.chooseZip();$('status').textContent='ZIP 已授权，请先预览再解压。'}catch(e){$('status').textContent=e.message}});
$('inspect').addEventListener('click',async()=>{try{requireBridge();if(!zipToken)throw new Error('请先选择 ZIP。');render(await bridge.preview(zipToken));$('status').textContent='所有条目均已通过安全预检。'}catch(e){$('status').textContent=e.message;$('summary').textContent='压缩包已在写入前被拦截。'}});
$('chooseDestination').addEventListener('click',async()=>{try{requireBridge();destinationToken=await bridge.chooseDestination();$('status').textContent='解压位置已授权，尚未写入任何文件。'}catch(e){$('status').textContent=e.message}});
$('extract').addEventListener('click',async()=>{try{requireBridge();if(!zipToken||!destinationToken)throw new Error('请先选择 ZIP 和解压位置。');if(!confirm('确定按“同名时重命名”策略解压已通过预检的 ZIP 吗？现有文件不会被覆盖。'))return;render(await bridge.extract(zipToken,destinationToken));$('status').textContent='解压完成；同名文件已按策略重命名。'}catch(e){$('status').textContent=e.message}});
$('chooseFiles').addEventListener('click',async()=>{try{requireBridge();filesToken=await bridge.chooseFiles();$('status').textContent='源文件已授权；只有在保存对话框确认后才会写入 ZIP。'}catch(e){$('status').textContent=e.message}});
$('create').addEventListener('click',async()=>{try{requireBridge();if(!filesToken)throw new Error('请先选择要压缩的文件。');if(!confirm('确定用所选文件创建不压缩存储的 ZIP 吗？'))return;const result=await bridge.create(filesToken);$('status').textContent=`已安全创建包含 ${result.entries} 个条目的 ZIP。`}catch(e){$('status').textContent=e.message}});
$('copy').addEventListener('click',async()=>{if(!plan)return;const text=JSON.stringify(plan,null,2);try{if(bridge?.copyText)await bridge.copyText(text);else await navigator.clipboard.writeText(text);$('status').textContent='解压预案已复制。'}catch{$('status').textContent='当前环境无法复制。'}});
