'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const { createExtensionManager } = require('../preload/extensionManager')

test('manages and synchronizes MCP servers without erasing unrelated config', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-extension-test-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const homeDir = path.join(root, 'home'); const manager = createExtensionManager({ homeDir, dataDir: path.join(root, 'data') })
  const claudePath = path.join(homeDir, '.claude.json'); await fs.mkdir(path.dirname(claudePath), { recursive: true }); await fs.writeFile(claudePath, JSON.stringify({ permissions: { allow: ['Bash'] } }))
  const item = await manager.saveMcp({ id: 'filesystem', name: 'Filesystem', command: 'npx', args: ['-y', 'server'], env: { ROOT: '/tmp' } })
  await assert.rejects(() => manager.saveMcp({ id: 'filesystem', name: 'Overwrite', command: 'evil' }, { createOnly: true }), /已存在/)
  assert.equal((await manager.listExtensions()).mcpServers[0].command, 'npx')
  await manager.setMcpEnabled(item.id, 'claude', true)
  const config = JSON.parse(await fs.readFile(claudePath, 'utf8'))
  assert.deepEqual(config.permissions, { allow: ['Bash'] })
  assert.equal(config.mcpServers.filesystem.command, 'npx')
  await manager.setMcpEnabled(item.id, 'claude-desktop', true)
  const desktopConfig = JSON.parse(await fs.readFile(path.join(homeDir, 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json'), 'utf8'))
  assert.equal(desktopConfig.mcpServers.filesystem.command, 'npx')
  await manager.setMcpEnabled(item.id, 'codex', true)
  assert.match(await fs.readFile(path.join(homeDir, '.codex', 'config.toml'), 'utf8'), /\[mcp_servers\.filesystem\]/)
  await manager.setMcpEnabled(item.id, 'grokbuild', true)
  const grok = await fs.readFile(path.join(homeDir, '.grok', 'config.toml'), 'utf8'); assert.match(grok, /\[mcp_servers\.filesystem\]/); assert.match(grok, /env = \{ "ROOT" = "\/tmp" \}/)
  await manager.removeMcp(item.id)
  const removed = JSON.parse(await fs.readFile(claudePath, 'utf8'))
  assert.equal(removed.mcpServers.filesystem, undefined)
})

test('imports MCP servers from fixed client configs, merges app flags and redacts Claude preview', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-mcp-import-test-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const homeDir = path.join(root, 'home'); const manager = createExtensionManager({ homeDir, dataDir: path.join(root, 'data') })
  await fs.mkdir(path.join(homeDir, '.codex'), { recursive: true })
  await fs.mkdir(path.join(homeDir, '.config', 'opencode'), { recursive: true })
  await fs.mkdir(path.join(homeDir, '.hermes'), { recursive: true })
  await fs.writeFile(path.join(homeDir, '.claude.json'), JSON.stringify({ keep: true, mcpServers: { shared: { command: 'node', args: ['claude.js'], env: { API_TOKEN: 'secret' } } } }))
  await fs.writeFile(path.join(homeDir, '.codex', 'config.toml'), '[mcp_servers.shared]\ncommand = "node"\nargs = ["codex.js"]\n\n[mcp_servers.remote]\nurl = "https://mcp.example.com"\nhttp_headers = { "Authorization" = "Bearer secret" }\n')
  await fs.writeFile(path.join(homeDir, '.config', 'opencode', 'opencode.json'), JSON.stringify({ mcp: { local: { type: 'local', command: ['node', 'local.js'], environment: { MODE: 'test' } } } }))
  await fs.writeFile(path.join(homeDir, '.hermes', 'config.yaml'), 'mcp_servers:\n  hermes-local:\n    command: node\n    args:\n      - hermes.js\n')

  const result = await manager.importMcpFromApps()
  assert.deepEqual(result.errors, [])
  assert.equal(result.imported.length, 4)
  assert.deepEqual(result.updated, ['codex:shared'])
  const listed = await manager.listExtensions()
  const shared = listed.mcpServers.find((item) => item.id === 'shared')
  assert.equal(shared.apps.claude, true); assert.equal(shared.apps.codex, true)
  assert.equal(listed.mcpServers.find((item) => item.id === 'remote').type, 'http')
  assert.deepEqual(listed.mcpServers.find((item) => item.id === 'local').args, ['local.js'])
  const status = await manager.getClaudeMcpStatus()
  assert.equal(status.serverCount, 1); assert.equal(status.userConfigExists, true)
  const preview = await manager.readClaudeMcpConfig()
  assert.match(preview, /••••••••/); assert.doesNotMatch(preview, /secret/)
  assert.equal(await manager.validateMcpCommand(process.execPath), true)
  assert.equal(await manager.validateMcpCommand('definitely-missing-ztools-command'), false)
})

test('manages prompts and synchronizes client-specific formats', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-prompt-test-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const homeDir = path.join(root, 'home'); const manager = createExtensionManager({ homeDir, dataDir: path.join(root, 'data') })
  const prompt = await manager.savePrompt({ id: 'review', name: 'Review', description: 'Review code', content: 'Review this change.' })
  await manager.setPromptEnabled(prompt.id, 'claude', true); await manager.setPromptEnabled(prompt.id, 'gemini', true)
  await manager.setPromptEnabled(prompt.id, 'grokbuild', true)
  assert.match(await fs.readFile(path.join(homeDir, '.claude', 'commands', 'review.md'), 'utf8'), /Review this change/)
  assert.match(await fs.readFile(path.join(homeDir, '.gemini', 'commands', 'review.toml'), 'utf8'), /prompt =/)
  assert.match(await fs.readFile(path.join(homeDir, '.grok', 'AGENTS.md'), 'utf8'), /Review this change/)
  const listed = await manager.listExtensions(); assert.equal(listed.prompts[0].apps.claude, true)
})

test('reads and imports fixed per-client global Prompt files without accepting arbitrary paths', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-prompt-import-test-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const homeDir = path.join(root, 'home'); const dataDir = path.join(root, 'data')
  const manager = createExtensionManager({ homeDir, dataDir })
  const claudePrompt = path.join(homeDir, '.claude', 'CLAUDE.md')
  await fs.mkdir(path.dirname(claudePrompt), { recursive: true })
  await fs.writeFile(claudePrompt, '# Existing instructions\n\nKeep changes focused.\n')

  assert.match(await manager.getCurrentPromptFileContent('claude'), /Keep changes focused/)
  assert.equal(await manager.getCurrentPromptFileContent('codex'), null)
  const imported = await manager.importPromptFromFile('claude')
  assert.match(imported.id, /^imported-\d+-[a-f0-9]{4}$/)
  assert.deepEqual(imported.apps, {})
  assert.match((await manager.listExtensions()).prompts[0].content, /Existing instructions/)
  await assert.rejects(() => manager.getCurrentPromptFileContent('../outside'), /暂不支持/)

  const linked = path.join(homeDir, '.codex', 'AGENTS.md')
  await fs.mkdir(path.dirname(linked), { recursive: true })
  await fs.symlink(claudePrompt, linked)
  await assert.rejects(() => manager.getCurrentPromptFileContent('codex'), /安全的普通文件/)
})
