const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { migrateDefaultDataDir } = require('../preload/pluginDataMigration')

test('moves the default userData tree into pluginData and removes the legacy root', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-plugin-data-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const legacy = path.join(root, 'userData', 'ztools-cc-switch')
  const pluginData = path.join(root, 'pluginData')
  fs.mkdirSync(path.join(legacy, 'skill-backups'), { recursive: true })
  fs.writeFileSync(path.join(legacy, 'providers.json'), '{"providers":[]}')
  fs.writeFileSync(path.join(legacy, 'skill-backups', 'meta.json'), '{}')

  const result = migrateDefaultDataDir({ getPath: (name) => name === 'pluginData' ? pluginData : '' }, legacy)
  assert.deepEqual(result, { path: pluginData, migrated: true, usingPluginData: true })
  assert.equal(fs.existsSync(legacy), false)
  assert.equal(fs.readFileSync(path.join(pluginData, 'providers.json'), 'utf8'), '{"providers":[]}')
  assert.equal(fs.existsSync(path.join(pluginData, '.cc-switch-plugin-data-migration-v1.json')), true)
})

test('keeps legacy data when pluginData contains a conflicting file', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-plugin-data-conflict-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const legacy = path.join(root, 'legacy')
  const pluginData = path.join(root, 'pluginData')
  fs.mkdirSync(legacy, { recursive: true })
  fs.mkdirSync(pluginData, { recursive: true })
  fs.writeFileSync(path.join(legacy, 'providers.json'), 'legacy')
  fs.writeFileSync(path.join(pluginData, 'providers.json'), 'different')

  const result = migrateDefaultDataDir({ getPath: () => pluginData }, legacy)
  assert.deepEqual(result, { path: legacy, migrated: false, usingPluginData: false })
  assert.equal(fs.existsSync(legacy), true)
})

test('ignores a conflicting legacy runtime because sidecar files are recreated', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-plugin-data-runtime-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const legacy = path.join(root, 'legacy')
  const pluginData = path.join(root, 'pluginData')
  fs.mkdirSync(path.join(legacy, 'runtime'), { recursive: true })
  fs.mkdirSync(path.join(pluginData, 'runtime'), { recursive: true })
  fs.writeFileSync(path.join(legacy, 'runtime', 'sidecar'), 'old')
  fs.writeFileSync(path.join(pluginData, 'runtime', 'sidecar'), 'new')
  fs.writeFileSync(path.join(legacy, 'providers.json'), 'providers')

  const result = migrateDefaultDataDir({ getPath: () => pluginData }, legacy)
  assert.equal(result.path, pluginData)
  assert.equal(fs.existsSync(legacy), false)
  assert.equal(fs.readFileSync(path.join(pluginData, 'runtime', 'sidecar'), 'utf8'), 'new')
  assert.equal(fs.readFileSync(path.join(pluginData, 'providers.json'), 'utf8'), 'providers')
})
