'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const { execFile: execFileCallback } = require('node:child_process')
const { promisify } = require('node:util')
const execFile = promisify(execFileCallback)
const { parseTimestamp, extractText, quoteShell, codexRequestHeadingPayload, extractCodexPromptFromIdeContext, codexTitleCandidate, createSessionManager } = require('../preload/sessionManager')

async function write(file, content) { await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, content) }
const line = (value) => `${JSON.stringify(value)}\n`

test('session helpers normalize timestamps, rich content and shell paths', () => {
  assert.equal(parseTimestamp(1700000000), 1700000000000)
  assert.equal(parseTimestamp('2026-07-22T00:00:00Z'), 1784678400000)
  assert.equal(extractText([{ type: 'text', text: 'one' }, { type: 'tool_use', name: 'read' }]), 'one\n[Tool: read]')
  assert.equal(quoteShell("/tmp/a'b"), "'/tmp/a'\"'\"'b'")
})

test('Codex VS Code IDE Context 按上游规则提取最后一个真实请求标题', () => {
  assert.equal(codexRequestHeadingPayload('## My request for Codex: Fix preview'), 'Fix preview')
  assert.equal(codexRequestHeadingPayload('## My request for Codex — 修复标题'), '修复标题')
  assert.equal(codexRequestHeadingPayload('My request for Codex: invalid'), null)
  assert.equal(extractCodexPromptFromIdeContext('# Context from my IDE setup:\n\n## Active selection:\n## My request for Codex:\nselection text\n\n## My request for Codex:\nUse the last request'), 'Use the last request')
  assert.equal(codexTitleCandidate('# Context from my IDE setup:\n\n## My request for Codex: Fix inline title'), 'Fix inline title')
  assert.equal(codexTitleCandidate('# Context from my IDE setup:\n\n## Active file: src/main.ts'), null)
  assert.equal(codexTitleCandidate('<environment_context>\n<cwd>/tmp</cwd>'), null)
})

test('scans and loads Claude, Codex, Gemini, OpenCode, OpenClaw, Hermes and GrokBuild sessions', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-sessions-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const home = path.join(root, 'home'); const xdg = path.join(root, 'xdg'); const data = path.join(root, 'data')
  const claude = path.join(home, '.claude/projects/p/claude-1.jsonl')
  await write(claude, line({ sessionId: 'claude-1', cwd: '/work/claude', timestamp: '2026-07-20T10:00:00Z', type: 'user', message: { role: 'user', content: 'Fix Claude issue' } }) + line({ timestamp: '2026-07-20T10:01:00Z', message: { role: 'assistant', content: 'Claude answer' } }))
  const codex = path.join(home, '.codex/sessions/2026/07/20/codex.jsonl')
  await write(codex, line({ type: 'session_meta', timestamp: '2026-07-20T11:00:00Z', payload: { id: 'codex-1', cwd: '/work/codex' } }) + line({ type: 'response_item', timestamp: '2026-07-20T11:01:00Z', payload: { type: 'message', role: 'user', content: [{ type: 'input_text', text: '# Context from my IDE setup:\n\n## Active file: src/main.ts\n\n## My request for Codex:\nFix Codex issue from VS Code' }] } }) + line({ type: 'response_item', timestamp: '2026-07-20T11:02:00Z', payload: { type: 'function_call', name: 'shell' } }))
  await write(path.join(home, '.codex/session_index.jsonl'), line({ id: 'codex-1', thread_name: 'Legacy renamed thread' }))
  await execFile('sqlite3', [path.join(home, '.codex/state_5.sqlite'), "CREATE TABLE threads(id TEXT,title TEXT,first_user_message TEXT); INSERT INTO threads VALUES('codex-1','VS Code renamed thread','Fix Codex issue from VS Code');"])
  const gemini = path.join(home, '.gemini/tmp/project/chats/session-gemini.json')
  await write(path.join(home, '.gemini/tmp/project/.project_root'), '/work/gemini')
  await write(gemini, JSON.stringify({ sessionId: 'gemini-1', startTime: '2026-07-20T12:00:00Z', lastUpdated: '2026-07-20T12:02:00Z', messages: [{ type: 'user', timestamp: '2026-07-20T12:00:00Z', content: 'Fix Gemini issue' }, { type: 'gemini', timestamp: '2026-07-20T12:01:00Z', content: 'Gemini answer', toolCalls: [{ name: 'search' }] }] }))
  const storage = path.join(xdg, 'opencode/storage'); const opencodeMeta = path.join(storage, 'session/project/ses_json.json')
  await write(opencodeMeta, JSON.stringify({ id: 'ses_json', title: 'OpenCode task', directory: '/work/opencode', time: { created: 1700000000000, updated: 1700000001000 } }))
  await write(path.join(storage, 'message/ses_json/msg_1.json'), JSON.stringify({ id: 'msg_1', role: 'user', time: { created: 1700000000000 } }))
  await write(path.join(storage, 'part/msg_1/part_1.json'), JSON.stringify({ type: 'text', text: 'OpenCode message' }))
  const openclaw = path.join(home, '.openclaw/agents/main/sessions/openclaw-1.jsonl')
  await write(openclaw, line({ type: 'session', id: 'openclaw-1', cwd: '/work/openclaw', timestamp: '2026-07-20T13:00:00Z' }) + line({ type: 'message', timestamp: '2026-07-20T13:01:00Z', message: { role: 'user', content: 'OpenClaw task' } }))
  await write(path.join(path.dirname(openclaw), 'sessions.json'), JSON.stringify({ key: { sessionId: 'openclaw-1', displayName: 'Claw display', sessionFile: openclaw } }))
  const hermes = path.join(home, '.hermes/sessions/hermes-1.jsonl')
  await write(hermes, line({ type: 'session', id: 'hermes-1', cwd: '/work/hermes', timestamp: '2026-07-20T14:00:00Z' }) + line({ role: 'user', content: 'Hermes task', timestamp: '2026-07-20T14:01:00Z' }))
  const hermesDb = path.join(home, '.hermes/state.db'); await execFile('sqlite3', [hermesDb, "CREATE TABLE sessions(id TEXT,title TEXT,cwd TEXT,started_at INTEGER,ended_at INTEGER); CREATE TABLE messages(session_id TEXT,role TEXT,content TEXT,created_at INTEGER); INSERT INTO sessions VALUES('hermes-sql','Hermes SQLite','/work/hermes-sql',1700000000,1700000010); INSERT INTO messages VALUES('hermes-sql','user','Hermes SQLite message',1700000001);"])
  const grokSummary = path.join(home, '.grok/sessions/project/grok-1/summary.json')
  await write(grokSummary, JSON.stringify({ info: { id: 'grok-1', cwd: '/work/grok' }, generated_title: 'Grok task', session_summary: 'Build with Grok', created_at: '2026-07-20T15:00:00Z', last_active_at: '2026-07-20T15:01:00Z' }))
  await write(path.join(path.dirname(grokSummary), 'chat_history.jsonl'), line({ type: 'user', content: [{ type: 'text', text: 'Grok message' }], timestamp: '2026-07-20T15:00:00Z' }) + line({ type: 'reasoning', content: 'private' }) + line({ type: 'assistant', content: 'Grok answer', timestamp: '2026-07-20T15:01:00Z' }))
  const db = path.join(xdg, 'opencode/opencode.db'); await fs.mkdir(path.dirname(db), { recursive: true })
  await execFile('sqlite3', [db, "CREATE TABLE session(id TEXT,title TEXT,directory TEXT,time_created INTEGER,time_updated INTEGER); CREATE TABLE message(id TEXT,session_id TEXT,time_created INTEGER,data TEXT); CREATE TABLE part(message_id TEXT,session_id TEXT,time_created INTEGER,data TEXT); INSERT INTO session VALUES('ses_sql','SQLite task','/work/sql',1700000000000,1700000002000); INSERT INTO message VALUES('msg_sql','ses_sql',1700000000000,'{\"role\":\"user\"}'); INSERT INTO part VALUES('msg_sql','ses_sql',1700000000000,'{\"type\":\"text\",\"text\":\"SQLite message\"}');"])
  const manager = createSessionManager({ homeDir: home, dataDir: data, xdgDataHome: xdg, hermesHome: path.join(home, '.hermes'), grokHome: path.join(home, '.grok') })
  const sessions = await manager.listSessions(); assert.deepEqual(new Set(sessions.map((item) => item.providerId)), new Set(['claude', 'codex', 'gemini', 'opencode', 'openclaw', 'hermes', 'grokbuild'])); assert.equal(sessions.length, 9)
  const byId = Object.fromEntries(sessions.map((item) => [item.sessionId, item]))
  assert.equal(byId['claude-1'].title, 'Fix Claude issue'); assert.equal(byId['codex-1'].title, 'VS Code renamed thread'); assert.equal(byId['openclaw-1'].title, 'Claw display'); assert.equal(byId['gemini-1'].projectDir, '/work/gemini')
  assert.match((await manager.getSessionMessages('claude', byId['claude-1'].sourcePath))[1].content, /Claude answer/)
  assert.match((await manager.getSessionMessages('codex', byId['codex-1'].sourcePath))[1].content, /Tool: shell/)
  assert.match((await manager.getSessionMessages('gemini', byId['gemini-1'].sourcePath))[1].content, /Tool: search/)
  assert.equal((await manager.getSessionMessages('opencode', byId.ses_json.sourcePath))[0].content, 'OpenCode message')
  assert.equal((await manager.getSessionMessages('opencode', byId.ses_sql.sourcePath))[0].content, 'SQLite message')
  assert.equal((await manager.getSessionMessages('hermes', byId['hermes-sql'].sourcePath))[0].content, 'Hermes SQLite message')
  assert.equal((await manager.getSessionMessages('grokbuild', byId['grok-1'].sourcePath)).length, 2)
})

test('deletion validates discovered paths, uses recoverable trash and backs up SQLite', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-session-delete-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const home = path.join(root, 'home'); const xdg = path.join(root, 'xdg'); const data = path.join(root, 'data'); const source = path.join(home, '.claude/projects/p/session.jsonl'); const sidecar = source.slice(0, -6)
  await write(source, line({ sessionId: 'delete-me', cwd: '/work', type: 'user', timestamp: '2026-07-20T00:00:00Z', message: { role: 'user', content: 'delete' } })); await write(path.join(sidecar, 'tool.txt'), 'result')
  const db = path.join(xdg, 'opencode/opencode.db'); await fs.mkdir(path.dirname(db), { recursive: true }); await execFile('sqlite3', [db, "CREATE TABLE session(id TEXT PRIMARY KEY,title TEXT,directory TEXT,time_created INTEGER,time_updated INTEGER); CREATE TABLE message(id TEXT PRIMARY KEY,session_id TEXT,time_created INTEGER,data TEXT); CREATE TABLE part(message_id TEXT,session_id TEXT,time_created INTEGER,data TEXT); INSERT INTO session VALUES('ses_del','Delete SQL','/work',1,2); INSERT INTO message VALUES('msg_del','ses_del',1,'{\"role\":\"user\"}'); INSERT INTO part VALUES('msg_del','ses_del',1,'{\"type\":\"text\",\"text\":\"restore me\"}');"])
  const manager = createSessionManager({ homeDir: home, dataDir: data, xdgDataHome: xdg })
  await assert.rejects(manager.deleteSession('claude', 'delete-me', '/tmp/foreign.jsonl'), /不存在|不匹配/)
  const deleted = await manager.deleteSession('claude', 'delete-me', source); assert.equal(deleted.recoverable, true); await assert.rejects(fs.access(source)); await assert.rejects(fs.access(sidecar)); assert.ok((await fs.readdir(path.join(data, 'session-trash'))).length >= 3)
  const trash = await manager.listTrash(); assert.equal(trash.length, 1); assert.equal(trash[0].sessionId, 'delete-me'); await manager.restoreTrash(deleted.trashId); assert.equal(await fs.readFile(source, 'utf8').then(Boolean), true); assert.equal(await fs.readFile(path.join(sidecar, 'tool.txt'), 'utf8'), 'result'); assert.equal((await manager.listTrash()).length, 0)
  const sqlSession = (await manager.listSessions()).find((item) => item.sessionId === 'ses_del'); const sqlDeleted = await manager.deleteSession('opencode', 'ses_del', sqlSession.sourcePath); assert.match(sqlDeleted.backupPath, /\.bak$/); assert.equal((await execFile('sqlite3', [db, 'SELECT count(*) FROM session;'])).stdout.trim(), '0')
  await execFile('sqlite3', [db, "INSERT INTO session VALUES('ses_new','Newer session','/later',3,4);"])
  assert.equal((await manager.listTrash()).find((item) => item.trashId === sqlDeleted.trashId).storageType, 'sqlite')
  await manager.restoreTrash(sqlDeleted.trashId)
  assert.equal((await execFile('sqlite3', [db, "SELECT count(*) FROM session WHERE id IN ('ses_del','ses_new');"])).stdout.trim(), '2')
  assert.equal((await execFile('sqlite3', [db, "SELECT count(*) FROM message WHERE session_id='ses_del';"])).stdout.trim(), '1')
  assert.equal((await execFile('sqlite3', [db, "SELECT count(*) FROM part WHERE session_id='ses_del';"])).stdout.trim(), '1')
})

test('GrokBuild 目录删除进入回收站并可整体恢复，Hermes SQLite 删除前备份', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-session-extra-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const home = path.join(root, 'home'); const data = path.join(root, 'data'); const grokHome = path.join(home, '.grok'); const hermesHome = path.join(home, '.hermes')
  const summary = path.join(grokHome, 'sessions/project/g1/summary.json'); await write(summary, JSON.stringify({ info: { id: 'g1', cwd: '/work' }, generated_title: 'Grok' })); await write(path.join(path.dirname(summary), 'chat_history.jsonl'), line({ type: 'user', content: 'hello' }))
  const hermesDb = path.join(hermesHome, 'state.db'); await fs.mkdir(hermesHome, { recursive: true }); await execFile('sqlite3', [hermesDb, "CREATE TABLE sessions(id TEXT,title TEXT); CREATE TABLE messages(session_id TEXT,role TEXT,content TEXT,created_at INTEGER); INSERT INTO sessions VALUES('h1','Hermes'); INSERT INTO messages VALUES('h1','user','hello',1);"])
  const manager = createSessionManager({ homeDir: home, dataDir: data, grokHome, hermesHome })
  const sessions = await manager.listSessions(); const grok = sessions.find((item) => item.sessionId === 'g1'); const hermes = sessions.find((item) => item.sessionId === 'h1')
  const removed = await manager.deleteSession('grokbuild', 'g1', grok.sourcePath); await assert.rejects(fs.access(path.dirname(summary))); await manager.restoreTrash(removed.trashId); assert.equal(JSON.parse(await fs.readFile(summary, 'utf8')).info.id, 'g1')
  const sqliteRemoved = await manager.deleteSession('hermes', 'h1', hermes.sourcePath); assert.match(sqliteRemoved.backupPath, /\.bak$/); assert.equal((await execFile('sqlite3', [hermesDb, 'SELECT count(*) FROM sessions;'])).stdout.trim(), '0')
  await execFile('sqlite3', [hermesDb, "INSERT INTO sessions VALUES('h2','Later Hermes');"])
  await manager.restoreTrash(sqliteRemoved.trashId)
  assert.equal((await execFile('sqlite3', [hermesDb, 'SELECT count(*) FROM sessions;'])).stdout.trim(), '2')
  assert.equal((await execFile('sqlite3', [hermesDb, "SELECT content FROM messages WHERE session_id='h1';"])).stdout.trim(), 'hello')
})

test('OpenClaw 索引损坏时中止删除并保留会话文件', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-openclaw-index-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const home = path.join(root, 'home'); const data = path.join(root, 'data')
  const source = path.join(home, '.openclaw/agents/main/sessions/openclaw-bad.jsonl')
  await write(source, line({ type: 'session', id: 'openclaw-bad', cwd: '/work', timestamp: '2026-07-20T13:00:00Z' }) + line({ type: 'message', timestamp: '2026-07-20T13:01:00Z', message: { role: 'user', content: 'keep me' } }))
  await write(path.join(path.dirname(source), 'sessions.json'), '{broken json')
  const manager = createSessionManager({ homeDir: home, dataDir: data })
  await assert.rejects(() => manager.deleteSession('openclaw', 'openclaw-bad', source), /索引失败/)
  assert.equal((await fs.stat(source)).isFile(), true)
})

test('OpenClaw 回收站清单写入失败时恢复索引和会话文件', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ztools-openclaw-rollback-')); t.after(() => fs.rm(root, { recursive: true, force: true }))
  const home = path.join(root, 'home'); const data = path.join(root, 'data')
  const source = path.join(home, '.openclaw/agents/main/sessions/openclaw-rollback.jsonl'); const indexPath = path.join(path.dirname(source), 'sessions.json')
  await write(source, line({ type: 'session', id: 'openclaw-rollback', cwd: '/work', timestamp: '2026-07-20T13:00:00Z' }) + line({ type: 'message', timestamp: '2026-07-20T13:01:00Z', message: { role: 'user', content: 'keep me' } }))
  await write(indexPath, JSON.stringify({ key: { sessionId: 'openclaw-rollback', sessionFile: source } }))
  const manager = createSessionManager({ homeDir: home, dataDir: data, beforeTrashManifestWrite: async () => { throw new Error('disk full') } })
  await assert.rejects(() => manager.deleteSession('openclaw', 'openclaw-rollback', source), /已恢复原状态/)
  assert.equal((await fs.stat(source)).isFile(), true)
  assert.equal(JSON.parse(await fs.readFile(indexPath, 'utf8')).key.sessionId, 'openclaw-rollback')
  assert.equal((await manager.listTrash()).length, 0)
})
