'use strict'
const MAX_CUES = 20000
function pad(value, width) { return String(Math.max(0, Math.floor(value))).padStart(width, '0') }
function parseTime(value) { const matched = String(value || '').trim().match(/^(?:(\d{1,3}):)?([0-5]\d):([0-5]\d)[,.](\d{1,3})$/); if (!matched) throw new Error('字幕时间格式无效：' + value); return (((Number(matched[1] || 0) * 3600) + Number(matched[2]) * 60 + Number(matched[3])) * 1000) + Number(matched[4].padEnd(3, '0')) }
function formatTime(milliseconds, separator) { const total = Math.max(0, Math.round(Number(milliseconds) || 0)); return pad(Math.floor(total / 3600000), 2) + ':' + pad(Math.floor(total % 3600000 / 60000), 2) + ':' + pad(Math.floor(total % 60000 / 1000), 2) + (separator || ',') + pad(total % 1000, 3) }
function normalizedLines(input) { return String(input || '').replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n').split('\n') }
function attachVttMeta(cues, meta) { Object.defineProperty(cues, 'vttMeta', { value: meta, enumerable: false, configurable: true }); return cues }
function propagateVttMeta(source, target) { if (source && source.vttMeta) attachVttMeta(target, source.vttMeta); return target }
function parseSrt(input) { const blocks = normalizedLines(input).join('\n').trim().split(/\n{2,}/).filter(Boolean); if (blocks.length > MAX_CUES) throw new RangeError('字幕条目过多'); return blocks.map((block, position) => { const lines = block.split('\n'); const timeIndex = lines.findIndex(line => line.includes('-->')); if (timeIndex < 0) throw new Error('第 ' + (position + 1) + ' 条字幕缺少时间范围'); const range = lines[timeIndex].split('-->').map(part => part.trim()); if (range.length !== 2) throw new Error('字幕时间范围无效'); return { id: lines.slice(0, timeIndex).join(' ').trim() || String(position + 1), start: parseTime(range[0]), end: parseTime(range[1]), text: lines.slice(timeIndex + 1).join('\n').trim() } }) }
function parseVtt(input) {
  const lines = normalizedLines(input); if (!/^WEBVTT(?:\s|$)/.test(lines[0] || '')) throw new Error('缺少 WEBVTT 文件头')
  const separator = lines.indexOf(''); const headerEnd = separator < 0 ? 1 : separator; const header = lines.slice(0, headerEnd).join('\n'); const blocks = (separator < 0 ? [] : lines.slice(separator + 1).join('\n').trim().split(/\n{2,}/)).filter(Boolean)
  const docs = []; const cues = []; const sequence = []
  for (const block of blocks) {
    if (/^(?:NOTE(?:[ \t].*)?|STYLE|REGION)(?:\n|$)/.test(block)) { docs.push(block); sequence.push({ type: 'doc', value: block }); continue }
    const cueLines = block.split('\n'); const timeIndex = cueLines.findIndex(line => line.includes('-->')); if (timeIndex < 0) throw new Error('第 ' + (cues.length + 1) + ' 条字幕缺少时间范围')
    const pieces = cueLines[timeIndex].split('-->'); if (pieces.length !== 2) throw new Error('VTT 时间范围无效'); const right = pieces[1].trim().match(/^(\S+)(?:\s+(.*))?$/); if (!right) throw new Error('VTT 结束时间无效')
    cues.push({ id: cueLines.slice(0, timeIndex).join(' ').trim() || null, start: parseTime(pieces[0].trim()), end: parseTime(right[1]), settings: right[2] || '', text: cueLines.slice(timeIndex + 1).join('\n').trim() }); sequence.push({ type: 'cue', index: cues.length - 1 })
  }
  if (cues.length > MAX_CUES) throw new RangeError('字幕条目过多'); return attachVttMeta(cues, { header, docs, sequence })
}
function parse(input, format) { return format === 'vtt' ? parseVtt(input) : parseSrt(input) }
function toSrt(cues) { return cues.map((cue, index) => (index + 1) + '\n' + formatTime(cue.start, ',') + ' --> ' + formatTime(cue.end, ',') + '\n' + String(cue.text || '').trim()).join('\n\n') + '\n' }
function toVtt(cues) { const meta = cues && cues.vttMeta; const header = meta && meta.header || 'WEBVTT'; const renderCue = cue => (cue.id ? String(cue.id).trim() + '\n' : '') + formatTime(cue.start, '.') + ' --> ' + formatTime(cue.end, '.') + (cue.settings ? ' ' + cue.settings : '') + '\n' + String(cue.text || '').trim(); const items = meta && meta.sequence ? meta.sequence.map(item => item.type === 'doc' ? item.value : renderCue(cues[item.index])).filter(Boolean) : cues.map(renderCue); return header + '\n\n' + items.join('\n\n') + '\n' }
function shift(cues, delta) { const next = cues.map(cue => { const duration = Math.max(0, cue.end - cue.start); const start = Math.max(0, cue.start + Number(delta || 0)); return { ...cue, start, end: Math.max(start, start + duration) } }); return propagateVttMeta(cues, next) }
function scale(cues, speed) { const factor = Number(speed); if (!Number.isFinite(factor) || factor <= 0 || factor > 100) throw new RangeError('速度倍率无效'); return propagateVttMeta(cues, cues.map(cue => ({ ...cue, start: Math.round(cue.start / factor), end: Math.round(cue.end / factor) }))) }
function qualityCheck(cues, options) { const min = Number.isFinite(options && options.minDuration) ? options.minDuration : 500; const max = Number.isFinite(options && options.maxDuration) ? options.maxDuration : 8000; const cps = Number.isFinite(options && options.maxCharsPerSecond) ? options.maxCharsPerSecond : 22; if (min < 0 || max <= 0 || cps <= 0 || max < min) throw new RangeError('质检阈值无效'); const findings = []; cues.forEach((cue,index) => { const duration = cue.end-cue.start; const text=String(cue.text||'').trim(); if(!text)findings.push({index,code:'EMPTY_TEXT'}); if(cue.end<cue.start)findings.push({index,code:'REVERSED'}); if(duration<min)findings.push({index,code:'TOO_SHORT'}); if(duration>max)findings.push({index,code:'TOO_LONG'}); if(duration>0&&text.replace(/\s/g,'').length/(duration/1000)>cps)findings.push({index,code:'FAST_READING'}); if(index&&cue.start<cues[index-1].end)findings.push({index,code:'OVERLAP'}) }); return findings }
module.exports = Object.freeze({ parseTime, formatTime, parseSrt, parseVtt, parse, toSrt, toVtt, shift, scale, qualityCheck })
