'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
test('subtitle findings are rendered via DOM textContent, not HTML templates', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8')
  assert.match(html, /<html lang="zh-CN">/)
  assert.match(html, /本地剪辑室/)
  assert.doesNotMatch(html, /LOCAL CUT ROOM|QC 检片/)
  assert.match(html, /n\.textContent='#'\+\(item\.index\+1\)/)
  assert.match(html, /MAX_RENDERED_FINDINGS=500/)
  assert.match(html, /items\.slice\(0,MAX_RENDERED_FINDINGS\)/)
  assert.match(html, /仅显示前/)
  assert.ok(!html.includes('.innerHTML'))
})
test('renderer maps stable machine codes to Chinese user-facing messages', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8')
  for (const [code, label] of Object.entries({ EMPTY_TEXT: '字幕文本为空', REVERSED: '结束时间早于开始时间', TOO_SHORT: '显示时长过短', TOO_LONG: '显示时长过长', FAST_READING: '阅读速度过快', OVERLAP: '与上一条字幕重叠' })) {
    assert.match(html, new RegExp(`${code}:'${label}'`))
  }
  assert.doesNotMatch(html, /\+'（'\+item\.code\+'）'/)
  assert.match(html, /findingLabels\[item\.code\]\|\|'未知质检问题'/)
  assert.match(html, /FFMPEG_UNAVAILABLE:'当前宿主未提供 FFmpeg 能力。'/)
  assert.doesNotMatch(html, /status\.textContent=r\.code/)
})
test('audio polling exposes cancellation, leftover backup warnings, and restore failures in Chinese', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8')
  assert.match(html, /'canceled'/)
  assert.match(html, /音轨提取已取消/)
  assert.match(html, /AUDIO_BACKUP_CLEANUP_FAILED/)
  assert.match(html, /旧备份/)
  assert.match(html, /未能清理，请手动检查/)
  assert.match(html, /AUDIO_BACKUP_RESTORE_FAILED/)
  assert.match(html, /旧文件未能自动恢复/)
  assert.match(html, /visibleFileName/)
  assert.doesNotMatch(html, /status\.textContent=job\.message/)
})
test('renderer surfaces retryable temporary cleanup and catches the initial entry promise', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8')
  assert.match(html, /id="retryCleanup" disabled>重试清理临时音轨/)
  assert.match(html, /AUDIO_TEMP_CLEANUP_FAILED:'音轨临时文件未能清理，请重试。'/)
  assert.match(html, /api\.pendingAudioCleanups\?\.\(\)/)
  assert.match(html, /api\.retryAudioCleanup\(cleanupJobId\)/)
  assert.match(html, /void consume\(api\.consumeEntry\(\)\)\.catch\(/)
  assert.doesNotMatch(html, /(?:^|\s)consume\(api\.consumeEntry\(\)\);/)
})
