import test from 'node:test';import assert from 'node:assert/strict';import {deflateRawSync}from 'node:zlib';import {existsSync}from 'node:fs';import {mkdtemp,readFile,readdir,symlink,writeFile}from 'node:fs/promises';import {tmpdir}from 'node:os';import path from 'node:path';import {createStoredZip,extractZipSafely,inspectZip,normalizeEntryName,collisionKey,planExtraction}from '../src/core/archive.mjs';
function put16(view,at,value){view.setUint16(at,value,true)}function put32(view,at,value){view.setUint32(at,value,true)}
function forgedDeflateZip(){const name=new TextEncoder().encode('bomb.txt'),raw=deflateRawSync(Buffer.alloc(1024*1024,65)),local=30+name.length,central=46+name.length,eocd=22,out=new Uint8Array(local+raw.length+central+eocd),v=new DataView(out.buffer);put32(v,0,0x04034b50);put16(v,4,20);put16(v,6,0x800);put16(v,8,8);put32(v,18,raw.length);put32(v,22,1);put16(v,26,name.length);out.set(name,30);out.set(raw,local);const c=local+raw.length;put32(v,c,0x02014b50);put16(v,c+4,20);put16(v,c+6,20);put16(v,c+8,0x800);put16(v,c+10,8);put32(v,c+20,raw.length);put32(v,c+24,1);put16(v,c+28,name.length);put32(v,c+42,0);out.set(name,c+46);const e=c+central;put32(v,e,0x06054b50);put16(v,e+8,1);put16(v,e+10,1);put32(v,e+12,central);put32(v,e+16,c);return out;}
test('path policy rejects traversal, Windows paths, reserved names, controls, ADS, and forbidden characters',()=>{for(const name of ['../x','/x','C:/x','\\\\server\\x','a\\b','a/../b','nul.txt','a/.','COM¹','com².txt','LPT³','folder/LPT².txt','safe.txt:hidden','folder/C:evil','line\nbreak.txt','tab\tname.txt','bad<name.txt','bad>name.txt','bad"name.txt','bad|name.txt','bad?name.txt','bad*name.txt'])assert.throws(()=>normalizeEntryName(name));assert.equal(normalizeEntryName('folder/file.txt'),'folder/file.txt');});
for(const platform of ['win32','darwin','linux'])test(`archive entry path contract is Windows-safe on ${platform}`,()=>{for(const name of ['COM¹','LPT².txt','folder/COM³.log','safe.txt:hidden','folder/C:evil','folder/bad?.txt','folder/control\u0001.txt'])assert.throws(()=>normalizeEntryName(name));assert.equal(normalizeEntryName('中文 文件夹/正常¹ 文件.txt'),'中文 文件夹/正常¹ 文件.txt');});
test('stored ZIP creates and round-trips a bounded plan',()=>{const bytes=createStoredZip([{name:'one.txt',data:'hello'},{name:'nested/two.txt',data:'world'}]);const plan=planExtraction(bytes);assert.equal(plan.entries.length,2);assert.equal(plan.total,10);});
test('case and unicode collisions fail before extraction',()=>{assert.throws(()=>createStoredZip([{name:'A.txt',data:'x'},{name:'a.txt',data:'y'}]));assert.equal(collisionKey('Café.txt'),collisionKey('Café.txt'));});
test('normalizes explicit directory entries without treating them as files',()=>{assert.equal(normalizeEntryName('folder/'),'folder/');assert.equal(collisionKey('folder/'),collisionKey('folder'));});
test('archive limits reject compression bombs and unsupported links from central metadata',()=>{const bytes=createStoredZip([{name:'x.txt',data:'tiny'}]);assert.ok(inspectZip(bytes));assert.throws(()=>inspectZip(bytes,{limits:{total:1}}));});
test('rejects symlink or device entries advertised by ZIP metadata',()=>{const bytes=createStoredZip([{name:'x.txt',data:'tiny'}]);const at=bytes.findIndex((_,i)=>bytes[i]===0x50&&bytes[i+1]===0x4b&&bytes[i+2]===1&&bytes[i+3]===2);new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).setUint32(at+38,0o120000<<16,true);assert.throws(()=>inspectZip(bytes),/不安全的特殊条目/);});
test('refuses a symlink output ancestor and writes normal files atomically',async()=>{const root=await mkdtemp(path.join(tmpdir(),'archive-'));const bytes=createStoredZip([{name:'safe/a.txt',data:'ok'}]);await extractZipSafely(bytes,root);assert.equal(await readFile(path.join(root,'safe','a.txt'),'utf8'),'ok');const blocked=await mkdtemp(path.join(tmpdir(),'archive-blocked-'));await symlink('/tmp',path.join(blocked,'safe'));await assert.rejects(extractZipSafely(bytes,blocked),/上级目录不安全/);});
test('refuses a symlink destination root and never overwrites a collision race',async()=>{const target=await mkdtemp(path.join(tmpdir(),'archive-target-')),linkRoot=path.join(tmpdir(),`archive-link-${Date.now()}`),bytes=createStoredZip([{name:'a.txt',data:'new'}]);await symlink(target,linkRoot);await assert.rejects(extractZipSafely(bytes,linkRoot),/解压目标根目录不安全/);const root=await mkdtemp(path.join(tmpdir(),'archive-race-'));await writeFile(path.join(root,'a.txt'),'old');await extractZipSafely(bytes,root);assert.equal(await readFile(path.join(root,'a.txt'),'utf8'),'old');assert.equal(await readFile(path.join(root,'a.txt (1)'),'utf8'),'new');});
test('bounds inflate before a forged central-directory size can allocate output',async()=>{const root=await mkdtemp(path.join(tmpdir(),'archive-bomb-'));await assert.rejects(extractZipSafely(forgedDeflateZip(),root));});
test('creates a large stored entry without argument spreading and rejects ZIP64 metadata',()=>{const bytes=createStoredZip([{name:'large.bin',data:new Uint8Array(512*1024)}]);assert.ok(bytes.byteLength>512*1024);const eocd=bytes.length-22,v=new DataView(bytes.buffer);put16(v,eocd+4,1);assert.throws(()=>inspectZip(bytes),/多磁盘/);});
test('rejects local header, checksum, and data-descriptor mismatches',async()=>{const base=createStoredZip([{name:'name.txt',data:'hello'}]),central=base.findIndex((_,i)=>base[i]===0x50&&base[i+1]===0x4b&&base[i+2]===1&&base[i+3]===2),root=await mkdtemp(path.join(tmpdir(),'archive-mismatch-'));const headerMismatch=base.slice();new DataView(headerMismatch.buffer).setUint32(central+16,1,true);await assert.rejects(extractZipSafely(headerMismatch,root),/本地文件头不匹配/);const nameMismatch=base.slice();nameMismatch[30]=120;await assert.rejects(extractZipSafely(nameMismatch,root),/本地文件名不匹配/);const crcMismatch=base.slice();crcMismatch[30+'name.txt'.length]=120;await assert.rejects(extractZipSafely(crcMismatch,root),/校验和不匹配/);const descriptor=base.slice();new DataView(descriptor.buffer).setUint16(central+8,0x808,true);assert.throws(()=>inspectZip(descriptor),/数据描述符/);});
test('preflight rejects local name/header/data overlap and directory record mismatches',()=>{const base=createStoredZip([{name:'name.txt',data:'hello'}]),central=base.findIndex((_,i)=>base[i]===0x50&&base[i+1]===0x4b&&base[i+2]===1&&base[i+3]===2);const localName=base.slice();localName[30]=120;assert.throws(()=>planExtraction(localName),/本地文件名不匹配/);const localHeader=base.slice();new DataView(localHeader.buffer).setUint16(8,8,true);assert.throws(()=>planExtraction(localHeader),/本地文件头不匹配/);const large=createStoredZip([{name:'large.txt',data:new Uint8Array(100000)}]),largeCentral=large.findIndex((_,i)=>large[i]===0x50&&large[i+1]===0x4b&&large[i+2]===1&&large[i+3]===2);assert.ok(largeCentral>65000);new DataView(large.buffer).setUint16(28,65000,true);assert.throws(()=>planExtraction(large),/本地文件头不匹配/);const directory=createStoredZip([{name:'abcd',data:''}]),directoryCentral=directory.findIndex((_,i)=>directory[i]===0x50&&directory[i+1]===0x4b&&directory[i+2]===1&&directory[i+3]===2);directory.set(new TextEncoder().encode('dir/'),30);directory.set(new TextEncoder().encode('dir/'),directoryCentral+46);new DataView(directory.buffer).setUint32(directoryCentral+38,0o40000<<16,true);assert.doesNotThrow(()=>planExtraction(directory));new DataView(directory.buffer).setUint16(8,8,true);assert.throws(()=>planExtraction(directory),/本地文件头不匹配/);});
test('session expiry rolls back a newly created explicit directory entry',async()=>{const bytes=createStoredZip([{name:'abcd',data:''}]),central=bytes.findIndex((_,i)=>bytes[i]===0x50&&bytes[i+1]===0x4b&&bytes[i+2]===1&&bytes[i+3]===2);bytes.set(new TextEncoder().encode('dir/'),30);bytes.set(new TextEncoder().encode('dir/'),central+46);new DataView(bytes.buffer).setUint32(central+38,0o40000<<16,true);const root=await mkdtemp(path.join(tmpdir(),'archive-directory-exit-')),created=path.join(root,'dir');const expired=Object.assign(new Error('expired'),{code:'SESSION_EXPIRED'});await assert.rejects(extractZipSafely(bytes,root,{assertActive(){if(existsSync(created))throw expired}}),{code:'SESSION_EXPIRED'});assert.deepEqual(await readdir(root),[]);});
test('session expiry rolls back files created by earlier archive entries',async()=>{const bytes=createStoredZip([{name:'one.txt',data:'one'},{name:'two.txt',data:'two'}]),root=await mkdtemp(path.join(tmpdir(),'archive-transaction-exit-')),first=path.join(root,'one.txt');const expired=Object.assign(new Error('expired'),{code:'SESSION_EXPIRED'});await assert.rejects(extractZipSafely(bytes,root,{assertActive(){if(existsSync(first))throw expired}}),{code:'SESSION_EXPIRED'});assert.deepEqual(await readdir(root),[]);});
