'use strict'

const crypto = require('node:crypto')

const DEFAULT_OPTIMIZER = Object.freeze({ enabled: false, thinkingOptimizer: true, cacheInjection: true })
const DEFAULT_COPILOT = Object.freeze({ enabled: true, requestClassification: true, toolResultMerging: true, compactDetection: true, deterministicRequestId: true, subagentDetection: true, warmupDowngrade: true, warmupModel: 'gpt-5-mini', stripThinking: true })

function normalizeOptimizer(value = {}) { return { enabled: Boolean(value.enabled), thinkingOptimizer: value.thinkingOptimizer !== false, cacheInjection: value.cacheInjection !== false } }
function normalizeCopilot(value = {}) { return { enabled: value.enabled !== false, requestClassification: value.requestClassification !== false, toolResultMerging: value.toolResultMerging !== false, compactDetection: value.compactDetection !== false, deterministicRequestId: value.deterministicRequestId !== false, subagentDetection: value.subagentDetection !== false, warmupDowngrade: value.warmupDowngrade !== false, warmupModel: String(value.warmupModel || 'gpt-5-mini').trim().slice(0, 200) || 'gpt-5-mini', stripThinking: value.stripThinking !== false } }
function appendBeta(body, beta) { const list = Array.isArray(body.anthropic_beta) ? body.anthropic_beta : []; if (!list.includes(beta)) list.push(beta); body.anthropic_beta = list }
function adaptiveModel(model) { return ['fable-5','mythos-5','mythos-preview','sonnet-5','opus-4-8','opus-4-7','opus-4-6','sonnet-4-6'].some((part) => String(model).toLowerCase().replace(/[._]/g, '-').includes(part)) }

function optimizeThinking(body) {
  const model = String(body.model || '').toLowerCase(); if (!model || model.includes('haiku')) return
  if (adaptiveModel(model)) { body.thinking = { type: 'adaptive' }; body.output_config = { effort: 'max' }; appendBeta(body, 'context-1m-2025-08-07'); return }
  const target = Math.max(0, (Number(body.max_tokens) || 16384) - 1)
  if (!body.thinking || body.thinking.type === 'disabled') body.thinking = { type: 'enabled', budget_tokens: target }
  else if (body.thinking.type === 'enabled' && (Number(body.thinking.budget_tokens) || 0) < target) body.thinking.budget_tokens = target
  appendBeta(body, 'interleaved-thinking-2025-05-14')
}
function cacheCount(body) { let count = 0; for (const item of body.tools || []) if (item?.cache_control) count++; for (const item of Array.isArray(body.system) ? body.system : []) if (item?.cache_control) count++; for (const message of body.messages || []) for (const item of Array.isArray(message.content) ? message.content : []) if (item?.cache_control) count++; return count }
function injectMessage(message) { if (!Array.isArray(message?.content)) return false; const block = [...message.content].reverse().find((item) => !['thinking','redacted_thinking'].includes(item?.type)); if (!block || block.cache_control || typeof block !== 'object') return false; block.cache_control = { type: 'ephemeral' }; return true }
function injectCache(body) {
  let budget = Math.max(0, 4 - cacheCount(body)); if (!budget) return
  if (Array.isArray(body.tools) && body.tools.length && !body.tools.at(-1).cache_control) { body.tools.at(-1).cache_control = { type: 'ephemeral' }; budget-- }
  if (budget && typeof body.system === 'string') body.system = [{ type: 'text', text: body.system }]
  if (budget && Array.isArray(body.system) && body.system.length && !body.system.at(-1).cache_control) { body.system.at(-1).cache_control = { type: 'ephemeral' }; budget-- }
  if (budget && Array.isArray(body.messages)) { for (let i = body.messages.length - 1; i >= 0; i--) if (injectMessage(body.messages[i])) { budget--; break } }
  if (budget && Array.isArray(body.messages) && body.messages.length >= 4) { let users = 0; for (let i = body.messages.length - 1; i >= 0; i--) if (body.messages[i]?.role === 'user' && ++users === 2) { injectMessage(body.messages[i]); break } }
}
function optimizeBedrockRequest(body, config) { const normalized = normalizeOptimizer(config); const result = structuredClone(body); if (!normalized.enabled) return result; if (normalized.thinkingOptimizer) optimizeThinking(result); if (normalized.cacheInjection) injectCache(result); return result }

function textOf(value) { if (typeof value === 'string') return value; if (!Array.isArray(value)) return ''; return value.filter((item) => item?.type === 'text').map((item) => item.text || '').join(' ') }
function systemText(body) { return textOf(body.system) }
function isCompact(body) { if (systemText(body).startsWith('You are a helpful AI assistant tasked with summarizing conversations')) return true; const last = body.messages?.at(-1); if (last?.role !== 'user') return false; const text = textOf(last.content); return text.includes('CRITICAL: Respond with TEXT ONLY. Do NOT call any tools.') || (text.includes('Pending Tasks:') && text.includes('Current Work:')) }
function isSubagent(body) { if (systemText(body).includes('__SUBAGENT_MARKER__')) return true; if ((body.messages || []).some((message) => message.role === 'user' && textOf(message.content).includes('__SUBAGENT_MARKER__'))) return true; return String(body.metadata?.user_id || '').includes('_agent_') }
function classify(body, hasBeta, config) { const compact = config.compactDetection && isCompact(body); const subagent = config.subagentDetection && isSubagent(body); const last = body.messages?.at(-1); const toolContinuation = last?.role === 'user' && Array.isArray(last.content) && last.content.some((item) => item?.type === 'tool_result'); const initiator = subagent || compact || toolContinuation ? 'agent' : 'user'; return { initiator, isCompact: compact, isSubagent: subagent, isWarmup: initiator === 'user' && hasBeta && !compact && (!Array.isArray(body.tools) || !body.tools.length) } }
function sanitizeOrphans(body) { const messages = body.messages || []; for (let i = 1; i < messages.length; i++) { const message = messages[i]; if (message?.role !== 'user' || !Array.isArray(message.content)) continue; const previous = messages[i - 1]; const ids = new Set(previous?.role === 'assistant' && Array.isArray(previous.content) ? previous.content.filter((item) => item?.type === 'tool_use').map((item) => item.id) : []); message.content = message.content.map((item) => { if (item?.type !== 'tool_result' || (item.tool_use_id && ids.has(item.tool_use_id))) return item; const content = typeof item.content === 'string' ? item.content : Array.isArray(item.content) ? item.content.map((part) => part?.text || '').join('\n') : ''; return { type: 'text', text: `[Tool result for ${item.tool_use_id || ''}]: ${content}` } }) } return body }
function appendText(result, text) { const value = String(text?.text || ''); if (!value.trim()) return; if (typeof result.content === 'string') result.content += `\n${value}`; else if (Array.isArray(result.content)) result.content.push({ type: 'text', text: value }); else result.content = value }
function mergeToolResults(body) { for (const message of body.messages || []) { if (message?.role !== 'user' || !Array.isArray(message.content)) continue; const results = message.content.filter((item) => item?.type === 'tool_result'); const texts = message.content.filter((item) => item?.type === 'text'); if (!results.length || !texts.length || results.length + texts.length !== message.content.length) continue; if (results.length === texts.length) texts.forEach((text, index) => appendText(results[index], text)); else texts.forEach((text) => appendText(results.at(-1), text)); message.content = results } const merged = []; for (const message of body.messages || []) { const only = message?.role === 'user' && Array.isArray(message.content) && message.content.length && message.content.every((item) => item?.type === 'tool_result'); const last = merged.at(-1); if (only && last?.role === 'user' && Array.isArray(last.content) && last.content.every((item) => item?.type === 'tool_result')) last.content.push(...message.content); else merged.push(message) } body.messages = merged; return body }
function stripThinking(body) { for (const message of body.messages || []) if (message?.role === 'assistant' && Array.isArray(message.content)) message.content = message.content.filter((item) => !['thinking','redacted_thinking'].includes(item?.type)); return body }
function sessionId(body, headers) { const userId = String(body.metadata?.user_id || ''); const marker = userId.indexOf('_session_'); return marker >= 0 && userId.slice(marker + 9) ? userId.slice(marker + 9) : String(body.metadata?.session_id || userId || headers['x-session-id'] || '') }
function uuidHash(prefix, value) { const bytes = Buffer.from(crypto.createHash('sha256').update(`${prefix}${value}`).digest().subarray(0, 16)); bytes[6] = (bytes[6] & 15) | 64; bytes[8] = (bytes[8] & 63) | 128; return `${bytes.toString('hex',0,4)}-${bytes.toString('hex',4,6)}-${bytes.toString('hex',6,8)}-${bytes.toString('hex',8,10)}-${bytes.toString('hex',10,16)}` }
function lastUserContent(body) { for (const message of [...(body.messages || [])].reverse()) { if (message?.role !== 'user') continue; if (typeof message.content === 'string') return message.content; const filtered = (message.content || []).filter((item) => item?.type !== 'tool_result').map((item) => { const copy = { ...item }; delete copy.cache_control; return copy }); if (filtered.length) return JSON.stringify(filtered) } return '' }
function optimizeCopilotRequest(body, headers = {}, inputConfig = {}) { const config = normalizeCopilot(inputConfig); let result = structuredClone(body); if (!config.enabled) return { body: result, headers: {}, classification: null }; const classification = classify(result, Boolean(headers['anthropic-beta']), config); result = sanitizeOrphans(result); if (config.toolResultMerging) result = mergeToolResults(result); if (config.stripThinking) result = stripThinking(result); if (config.warmupDowngrade && classification.isWarmup) result.model = config.warmupModel; const id = sessionId(body, headers); const patch = {}; if (config.requestClassification) patch['x-initiator'] = classification.initiator; if (classification.isSubagent) patch['x-interaction-type'] = 'conversation-subagent'; if (config.deterministicRequestId) { const content = lastUserContent(result); const requestId = content ? uuidHash('', `${id}${content}`) : crypto.randomUUID(); patch['x-request-id'] = requestId; patch['x-agent-task-id'] = requestId } if (id) patch['x-interaction-id'] = uuidHash('interaction:', id); return { body: result, headers: patch, classification } }

module.exports = { DEFAULT_OPTIMIZER, DEFAULT_COPILOT, normalizeOptimizer, normalizeCopilot, optimizeBedrockRequest, optimizeCopilotRequest, _internal: { adaptiveModel, injectCache, classify, sanitizeOrphans, mergeToolResults, stripThinking, sessionId, uuidHash } }
