/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import ADD from "../../operations/ADD.mjs";
import AND from "../../operations/AND.mjs";
import AddLineNumbers from "../../operations/AddLineNumbers.mjs";
import AlternatingCaps from "../../operations/AlternatingCaps.mjs";
import BaconCipherDecode from "../../operations/BaconCipherDecode.mjs";
import BaconCipherEncode from "../../operations/BaconCipherEncode.mjs";
import BitShiftLeft from "../../operations/BitShiftLeft.mjs";
import BitShiftRight from "../../operations/BitShiftRight.mjs";
import CNIDVerify from "../../operations/CNIDVerify.mjs";
import CRCChecksum from "../../operations/CRCChecksum.mjs";
import CSVToJSON from "../../operations/CSVToJSON.mjs";
import CaretMdecode from "../../operations/CaretMdecode.mjs";
import CartesianProduct from "../../operations/CartesianProduct.mjs";
import ChangeIPFormat from "../../operations/ChangeIPFormat.mjs";
import ChiSquare from "../../operations/ChiSquare.mjs";
import Comment from "../../operations/Comment.mjs";
import ConditionalJump from "../../operations/ConditionalJump.mjs";
import ConvertArea from "../../operations/ConvertArea.mjs";
import ConvertDataUnits from "../../operations/ConvertDataUnits.mjs";
import ConvertDistance from "../../operations/ConvertDistance.mjs";
import ConvertLeetSpeak from "../../operations/ConvertLeetSpeak.mjs";
import ConvertMass from "../../operations/ConvertMass.mjs";
import ConvertSpeed from "../../operations/ConvertSpeed.mjs";
import ConvertToNATOAlphabet from "../../operations/ConvertToNATOAlphabet.mjs";
import CountOccurrences from "../../operations/CountOccurrences.mjs";
import DNSOverHTTPS from "../../operations/DNSOverHTTPS.mjs";
import DateTimeDelta from "../../operations/DateTimeDelta.mjs";
import DechunkHTTPResponse from "../../operations/DechunkHTTPResponse.mjs";
import DecodeNetBIOSName from "../../operations/DecodeNetBIOSName.mjs";
import DefangIPAddresses from "../../operations/DefangIPAddresses.mjs";
import DefangURL from "../../operations/DefangURL.mjs";
import DetectFileType from "../../operations/DetectFileType.mjs";
import Divide from "../../operations/Divide.mjs";
import DropBytes from "../../operations/DropBytes.mjs";
import DropNthBytes from "../../operations/DropNthBytes.mjs";
import ELFInfo from "../../operations/ELFInfo.mjs";
import EncodeNetBIOSName from "../../operations/EncodeNetBIOSName.mjs";
import EscapeString from "../../operations/EscapeString.mjs";
import EscapeUnicodeCharacters from "../../operations/EscapeUnicodeCharacters.mjs";
import ExpandAlphabetRange from "../../operations/ExpandAlphabetRange.mjs";
import ExtractFiles from "../../operations/ExtractFiles.mjs";
import ExtractID3 from "../../operations/ExtractID3.mjs";
import FangURL from "../../operations/FangURL.mjs";
import FernetDecrypt from "../../operations/FernetDecrypt.mjs";
import FernetEncrypt from "../../operations/FernetEncrypt.mjs";
import FileTree from "../../operations/FileTree.mjs";
import Fork from "../../operations/Fork.mjs";
import FormatMACAddresses from "../../operations/FormatMACAddresses.mjs";
import FrequencyDistribution from "../../operations/FrequencyDistribution.mjs";
import FromBCD from "../../operations/FromBCD.mjs";
import FromBase from "../../operations/FromBase.mjs";
import FromBase32 from "../../operations/FromBase32.mjs";
import FromBase45 from "../../operations/FromBase45.mjs";
import FromBase58 from "../../operations/FromBase58.mjs";
import FromBase62 from "../../operations/FromBase62.mjs";
import FromBase64 from "../../operations/FromBase64.mjs";
import FromBase85 from "../../operations/FromBase85.mjs";
import FromBase92 from "../../operations/FromBase92.mjs";
import FromBech32 from "../../operations/FromBech32.mjs";
import FromBinary from "../../operations/FromBinary.mjs";
import FromBraille from "../../operations/FromBraille.mjs";
import FromCaseInsensitiveRegex from "../../operations/FromCaseInsensitiveRegex.mjs";
import FromCharcode from "../../operations/FromCharcode.mjs";
import FromDecimal from "../../operations/FromDecimal.mjs";
import FromFloat from "../../operations/FromFloat.mjs";
import FromHex from "../../operations/FromHex.mjs";
import FromHexContent from "../../operations/FromHexContent.mjs";
import FromHexdump from "../../operations/FromHexdump.mjs";
import FromModhex from "../../operations/FromModhex.mjs";
import FromMorseCode from "../../operations/FromMorseCode.mjs";
import FromOctal from "../../operations/FromOctal.mjs";
import FromQuotedPrintable from "../../operations/FromQuotedPrintable.mjs";
import FromUNIXTimestamp from "../../operations/FromUNIXTimestamp.mjs";
import FuzzyMatch from "../../operations/FuzzyMatch.mjs";
import GenerateDeBruijnSequence from "../../operations/GenerateDeBruijnSequence.mjs";
import GenerateHOTP from "../../operations/GenerateHOTP.mjs";
import GenerateLoremIpsum from "../../operations/GenerateLoremIpsum.mjs";
import GenerateTOTP from "../../operations/GenerateTOTP.mjs";
import GetAllCasings from "../../operations/GetAllCasings.mjs";
import GetTime from "../../operations/GetTime.mjs";
import GroupIPAddresses from "../../operations/GroupIPAddresses.mjs";
import HTMLToText from "../../operations/HTMLToText.mjs";
import HTTPRequest from "../../operations/HTTPRequest.mjs";
import HammingDistance from "../../operations/HammingDistance.mjs";
import HaversineDistance from "../../operations/HaversineDistance.mjs";
import Head from "../../operations/Head.mjs";
import IPv6TransitionAddresses from "../../operations/IPv6TransitionAddresses.mjs";
import IndexOfCoincidence from "../../operations/IndexOfCoincidence.mjs";
import JSONToCSV from "../../operations/JSONToCSV.mjs";
import JSONtoYAML from "../../operations/JSONtoYAML.mjs";
import Jump from "../../operations/Jump.mjs";
import Label from "../../operations/Label.mjs";
import LevenshteinDistance from "../../operations/LevenshteinDistance.mjs";
import LuhnChecksum from "../../operations/LuhnChecksum.mjs";
import MIMEDecoding from "../../operations/MIMEDecoding.mjs";
import Magic from "../../operations/Magic.mjs";
import Mean from "../../operations/Mean.mjs";
import Median from "../../operations/Median.mjs";
import Merge from "../../operations/Merge.mjs";
import MicrosoftScriptDecoder from "../../operations/MicrosoftScriptDecoder.mjs";
import Multiply from "../../operations/Multiply.mjs";
import NOT from "../../operations/NOT.mjs";
import Numberwang from "../../operations/Numberwang.mjs";
import OR from "../../operations/OR.mjs";
import OffsetChecker from "../../operations/OffsetChecker.mjs";
import PEMToHex from "../../operations/PEMToHex.mjs";
import PHPDeserialize from "../../operations/PHPDeserialize.mjs";
import PHPSerialize from "../../operations/PHPSerialize.mjs";
import PLISTViewer from "../../operations/PLISTViewer.mjs";
import PadLines from "../../operations/PadLines.mjs";
import ParseColourCode from "../../operations/ParseColourCode.mjs";
import ParseDateTime from "../../operations/ParseDateTime.mjs";
import ParseIPRange from "../../operations/ParseIPRange.mjs";
import ParseIPv4Header from "../../operations/ParseIPv4Header.mjs";
import ParseIPv6Address from "../../operations/ParseIPv6Address.mjs";
import ParseSSHHostKey from "../../operations/ParseSSHHostKey.mjs";
import ParseTCP from "../../operations/ParseTCP.mjs";
import ParseTLSRecord from "../../operations/ParseTLSRecord.mjs";
import ParseTLV from "../../operations/ParseTLV.mjs";
import ParseUDP from "../../operations/ParseUDP.mjs";
import ParseUNIXFilePermissions from "../../operations/ParseUNIXFilePermissions.mjs";
import PlayMedia from "../../operations/PlayMedia.mjs";
import PowerSet from "../../operations/PowerSet.mjs";
import RAKE from "../../operations/RAKE.mjs";
import ROT13 from "../../operations/ROT13.mjs";
import ROT13BruteForce from "../../operations/ROT13BruteForce.mjs";
import ROT47 from "../../operations/ROT47.mjs";
import ROT47BruteForce from "../../operations/ROT47BruteForce.mjs";
import ROT8000 from "../../operations/ROT8000.mjs";
import RemoveDiacritics from "../../operations/RemoveDiacritics.mjs";
import RemoveLineNumbers from "../../operations/RemoveLineNumbers.mjs";
import RemoveNullBytes from "../../operations/RemoveNullBytes.mjs";
import RemoveWhitespace from "../../operations/RemoveWhitespace.mjs";
import Return from "../../operations/Return.mjs";
import Reverse from "../../operations/Reverse.mjs";
import RoarCipherDecode from "../../operations/RoarCipherDecode.mjs";
import RoarCipherEncode from "../../operations/RoarCipherEncode.mjs";
import RotateLeft from "../../operations/RotateLeft.mjs";
import RotateRight from "../../operations/RotateRight.mjs";
import SUB from "../../operations/SUB.mjs";
import ScanForEmbeddedFiles from "../../operations/ScanForEmbeddedFiles.mjs";
import SetDifference from "../../operations/SetDifference.mjs";
import SetIntersection from "../../operations/SetIntersection.mjs";
import SetUnion from "../../operations/SetUnion.mjs";
import ShowBase64Offsets from "../../operations/ShowBase64Offsets.mjs";
import Shuffle from "../../operations/Shuffle.mjs";
import Sleep from "../../operations/Sleep.mjs";
import Sort from "../../operations/Sort.mjs";
import Split from "../../operations/Split.mjs";
import StandardDeviation from "../../operations/StandardDeviation.mjs";
import StripHTMLTags from "../../operations/StripHTMLTags.mjs";
import StripHTTPHeaders from "../../operations/StripHTTPHeaders.mjs";
import StripIPv4Header from "../../operations/StripIPv4Header.mjs";
import StripTCPHeader from "../../operations/StripTCPHeader.mjs";
import StripUDPHeader from "../../operations/StripUDPHeader.mjs";
import Subsection from "../../operations/Subsection.mjs";
import Substitute from "../../operations/Substitute.mjs";
import Subtract from "../../operations/Subtract.mjs";
import Sum from "../../operations/Sum.mjs";
import SwapCase from "../../operations/SwapCase.mjs";
import SwapEndianness from "../../operations/SwapEndianness.mjs";
import SymmetricDifference from "../../operations/SymmetricDifference.mjs";
import Tail from "../../operations/Tail.mjs";
import TakeBytes from "../../operations/TakeBytes.mjs";
import TakeNthBytes from "../../operations/TakeNthBytes.mjs";
import ToBCD from "../../operations/ToBCD.mjs";
import ToBase from "../../operations/ToBase.mjs";
import ToBase32 from "../../operations/ToBase32.mjs";
import ToBase45 from "../../operations/ToBase45.mjs";
import ToBase58 from "../../operations/ToBase58.mjs";
import ToBase62 from "../../operations/ToBase62.mjs";
import ToBase64 from "../../operations/ToBase64.mjs";
import ToBase85 from "../../operations/ToBase85.mjs";
import ToBase92 from "../../operations/ToBase92.mjs";
import ToBech32 from "../../operations/ToBech32.mjs";
import ToBinary from "../../operations/ToBinary.mjs";
import ToBraille from "../../operations/ToBraille.mjs";
import ToCNNumberUpperCase from "../../operations/ToCNNumberUpperCase.mjs";
import ToCaseInsensitiveRegex from "../../operations/ToCaseInsensitiveRegex.mjs";
import ToCharcode from "../../operations/ToCharcode.mjs";
import ToDecimal from "../../operations/ToDecimal.mjs";
import ToFloat from "../../operations/ToFloat.mjs";
import ToHex from "../../operations/ToHex.mjs";
import ToHexContent from "../../operations/ToHexContent.mjs";
import ToHexdump from "../../operations/ToHexdump.mjs";
import ToLowerCase from "../../operations/ToLowerCase.mjs";
import ToModhex from "../../operations/ToModhex.mjs";
import ToMorseCode from "../../operations/ToMorseCode.mjs";
import ToOctal from "../../operations/ToOctal.mjs";
import ToQuotedPrintable from "../../operations/ToQuotedPrintable.mjs";
import ToTable from "../../operations/ToTable.mjs";
import ToUNIXTimestamp from "../../operations/ToUNIXTimestamp.mjs";
import ToUpperCase from "../../operations/ToUpperCase.mjs";
import TranslateDateTimeFormat from "../../operations/TranslateDateTimeFormat.mjs";
import UNIXTimestampToWindowsFiletime from "../../operations/UNIXTimestampToWindowsFiletime.mjs";
import UnescapeString from "../../operations/UnescapeString.mjs";
import UnescapeUnicodeCharacters from "../../operations/UnescapeUnicodeCharacters.mjs";
import UnicodeTextFormat from "../../operations/UnicodeTextFormat.mjs";
import Unique from "../../operations/Unique.mjs";
import VarIntDecode from "../../operations/VarIntDecode.mjs";
import VarIntEncode from "../../operations/VarIntEncode.mjs";
import WindowsFiletimeToUNIXTimestamp from "../../operations/WindowsFiletimeToUNIXTimestamp.mjs";
import XKCDRandomNumber from "../../operations/XKCDRandomNumber.mjs";
import XOR from "../../operations/XOR.mjs";
import XORBruteForce from "../../operations/XORBruteForce.mjs";
import YAMLToJSON from "../../operations/YAMLToJSON.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Default = {
    "ADD": ADD,
    "AND": AND,
    "添加行号": AddLineNumbers,
    "交替大小写": AlternatingCaps,
    "培根密码解密": BaconCipherDecode,
    "培根密码加密": BaconCipherEncode,
    "按位左移": BitShiftLeft,
    "按位右移": BitShiftRight,
    "身份证校验位验证": CNIDVerify,
    "CRC校验和": CRCChecksum,
    "CSV转JSON": CSVToJSON,
    "Caret/M-解码": CaretMdecode,
    "笛卡儿积": CartesianProduct,
    "IP地址格式转换": ChangeIPFormat,
    "卡方分布": ChiSquare,
    "Comment": Comment,
    "Conditional Jump": ConditionalJump,
    "单位转换：面积": ConvertArea,
    "单位转换：数据": ConvertDataUnits,
    "单位转换：距离": ConvertDistance,
    "Leet Speak转换": ConvertLeetSpeak,
    "单位转换：质量": ConvertMass,
    "单位转换：速度": ConvertSpeed,
    "转换为北约音标字母": ConvertToNATOAlphabet,
    "计数": CountOccurrences,
    "DNS over HTTPS": DNSOverHTTPS,
    "DateTime推算": DateTimeDelta,
    "合并HTTP响应分块": DechunkHTTPResponse,
    "NetBIOS名称解码": DecodeNetBIOSName,
    "IP地址无效化": DefangIPAddresses,
    "URL无效化": DefangURL,
    "检测文件类型": DetectFileType,
    "求商": Divide,
    "删除字节": DropBytes,
    "删除每N个字节": DropNthBytes,
    "ELF信息": ELFInfo,
    "NetBIOS名称编码": EncodeNetBIOSName,
    "转义字符串": EscapeString,
    "Unicode字符转义": EscapeUnicodeCharacters,
    "扩写字母范围": ExpandAlphabetRange,
    "提取文件": ExtractFiles,
    "提取ID3": ExtractID3,
    "URL无效化恢复": FangURL,
    "Fernet解密": FernetDecrypt,
    "Fernet加密": FernetEncrypt,
    "文件树": FileTree,
    "Fork": Fork,
    "MAC地址格式化": FormatMACAddresses,
    "频率分布": FrequencyDistribution,
    "BCD码解码": FromBCD,
    "其它进制数转十进制": FromBase,
    "Base32解码": FromBase32,
    "Base45解码": FromBase45,
    "Base58解码": FromBase58,
    "Base62解码": FromBase62,
    "Base64解码": FromBase64,
    "Base85解码": FromBase85,
    "Base92解码": FromBase92,
    "Bech32解码": FromBech32,
    "二进制转字符": FromBinary,
    "盲文解码": FromBraille,
    "从大小写不敏感正则恢复": FromCaseInsensitiveRegex,
    "从字符码提取": FromCharcode,
    "十进制转字符": FromDecimal,
    "浮点数转字符": FromFloat,
    "十六进制转字符": FromHex,
    "Snort Content解码": FromHexContent,
    "从Hexdump提取": FromHexdump,
    "Modhex解码": FromModhex,
    "摩尔斯电码解码": FromMorseCode,
    "八进制转字符": FromOctal,
    "QP解码": FromQuotedPrintable,
    "从UNIX时间戳提取": FromUNIXTimestamp,
    "模糊匹配": FuzzyMatch,
    "生成德布鲁因序列": GenerateDeBruijnSequence,
    "生成HOTP": GenerateHOTP,
    "生成Lorem Ipsum": GenerateLoremIpsum,
    "生成TOTP": GenerateTOTP,
    "大小写穷举": GetAllCasings,
    "获取当前时间": GetTime,
    "IP地址分组": GroupIPAddresses,
    "HTML转文本": HTMLToText,
    "HTTP请求": HTTPRequest,
    "汉明距离": HammingDistance,
    "半正矢距离": HaversineDistance,
    "Head": Head,
    "IPv6过渡地址": IPv6TransitionAddresses,
    "重合因子": IndexOfCoincidence,
    "JSON转CSV": JSONToCSV,
    "JSON转YAML": JSONtoYAML,
    "Jump": Jump,
    "Label": Label,
    "莱文斯坦距离": LevenshteinDistance,
    "Luhn校验和": LuhnChecksum,
    "MIME解码": MIMEDecoding,
    "Magic": Magic,
    "求平均": Mean,
    "求中位数": Median,
    "Merge": Merge,
    "Microsoft Script解码": MicrosoftScriptDecoder,
    "求积": Multiply,
    "NOT": NOT,
    "Numberwang": Numberwang,
    "OR": OR,
    "偏移检测": OffsetChecker,
    "PEM转十六进制": PEMToHex,
    "PHP反序列化": PHPDeserialize,
    "PHP Serialize": PHPSerialize,
    "P-list查看器": PLISTViewer,
    "填充行": PadLines,
    "解析颜色代码": ParseColourCode,
    "解析DateTime": ParseDateTime,
    "解析IP范围": ParseIPRange,
    "解析IPv4标头": ParseIPv4Header,
    "解析IPv6地址": ParseIPv6Address,
    "解析SSH主机密钥": ParseSSHHostKey,
    "解析TCP": ParseTCP,
    "解析TLS记录": ParseTLSRecord,
    "解析TLV": ParseTLV,
    "解析UDP": ParseUDP,
    "解析UNIX文件权限": ParseUNIXFilePermissions,
    "播放媒体文件": PlayMedia,
    "幂集": PowerSet,
    "RAKE": RAKE,
    "ROT13": ROT13,
    "ROT13暴力破解": ROT13BruteForce,
    "ROT47": ROT47,
    "ROT47暴力破解": ROT47BruteForce,
    "ROT8000": ROT8000,
    "移除变音符号": RemoveDiacritics,
    "移除行号": RemoveLineNumbers,
    "移除空字节": RemoveNullBytes,
    "移除空白字符": RemoveWhitespace,
    "Return": Return,
    "反转": Reverse,
    "兽音译者解密": RoarCipherDecode,
    "兽音译者加密": RoarCipherEncode,
    "循环左移": RotateLeft,
    "循环右移": RotateRight,
    "SUB": SUB,
    "扫描嵌入文件": ScanForEmbeddedFiles,
    "补集": SetDifference,
    "交集": SetIntersection,
    "并集": SetUnion,
    "显示Base64偏移形式": ShowBase64Offsets,
    "乱序": Shuffle,
    "Sleep": Sleep,
    "排序": Sort,
    "拆分": Split,
    "求标准差": StandardDeviation,
    "移除HTML标签": StripHTMLTags,
    "移除HTTP标头": StripHTTPHeaders,
    "移除IPv4标头": StripIPv4Header,
    "移除TCP标头": StripTCPHeader,
    "移除UDP标头": StripUDPHeader,
    "Subsection": Subsection,
    "替换密码": Substitute,
    "求差": Subtract,
    "求和": Sum,
    "大小写互换": SwapCase,
    "端序转换": SwapEndianness,
    "对称差": SymmetricDifference,
    "Tail": Tail,
    "提取字节": TakeBytes,
    "提取每N个字节": TakeNthBytes,
    "BCD码编码": ToBCD,
    "十进制数转其它进制": ToBase,
    "Base32编码": ToBase32,
    "Base45编码": ToBase45,
    "Base58编码": ToBase58,
    "Base62编码": ToBase62,
    "Base64编码": ToBase64,
    "Base85编码": ToBase85,
    "Base92编码": ToBase92,
    "Bech32编码": ToBech32,
    "字符转二进制": ToBinary,
    "盲文编码": ToBraille,
    "转换为大写数字": ToCNNumberUpperCase,
    "转换为大小写不敏感正则": ToCaseInsensitiveRegex,
    "转换为字符码": ToCharcode,
    "字符转十进制": ToDecimal,
    "字符转浮点数": ToFloat,
    "字符转十六进制": ToHex,
    "Snort Content编码": ToHexContent,
    "转换到Hexdump": ToHexdump,
    "转换为小写": ToLowerCase,
    "Modhex编码": ToModhex,
    "摩尔斯电码编码": ToMorseCode,
    "字符转八进制": ToOctal,
    "QP编码": ToQuotedPrintable,
    "转换为表格": ToTable,
    "转换到UNIX时间戳": ToUNIXTimestamp,
    "转换为大写": ToUpperCase,
    "转换DateTime格式": TranslateDateTimeFormat,
    "UNIX时间戳转Windows Filetime": UNIXTimestampToWindowsFiletime,
    "字符串转义恢复": UnescapeString,
    "Unicode转义恢复": UnescapeUnicodeCharacters,
    "Unicode文本格式": UnicodeTextFormat,
    "去重": Unique,
    "VarInt解码": VarIntDecode,
    "VarInt编码": VarIntEncode,
    "Windows Filetime转UNIX时间戳": WindowsFiletimeToUNIXTimestamp,
    "XKCD Random Number": XKCDRandomNumber,
    "XOR": XOR,
    "XOR暴力破解": XORBruteForce,
    "YAML转JSON": YAMLToJSON,
};

export default OpModules;
