/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import Jq from "../../operations/Jq.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Jq = {
    "Jq": Jq,
};

export default OpModules;
