/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import GeneratePGPKeyPair from "../../operations/GeneratePGPKeyPair.mjs";
import PGPDecrypt from "../../operations/PGPDecrypt.mjs";
import PGPDecryptAndVerify from "../../operations/PGPDecryptAndVerify.mjs";
import PGPEncrypt from "../../operations/PGPEncrypt.mjs";
import PGPEncryptAndSign from "../../operations/PGPEncryptAndSign.mjs";
import PGPVerify from "../../operations/PGPVerify.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PGP = {
    "生成PGP密钥对": GeneratePGPKeyPair,
    "PGP解密": PGPDecrypt,
    "PGP解密并验证": PGPDecryptAndVerify,
    "PGP加密": PGPEncrypt,
    "PGP加密并签名": PGPEncryptAndSign,
    "PGP验证": PGPVerify,
};

export default OpModules;
