/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import AvroToJSON from "../../operations/AvroToJSON.mjs";
import BSONDeserialise from "../../operations/BSONDeserialise.mjs";
import BSONSerialise from "../../operations/BSONSerialise.mjs";
import CBORDecode from "../../operations/CBORDecode.mjs";
import CBOREncode from "../../operations/CBOREncode.mjs";
import ParseObjectIDTimestamp from "../../operations/ParseObjectIDTimestamp.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Serialise = {
    "Avro转JSON": AvroToJSON,
    "BSON反序列化": BSONDeserialise,
    "BSON序列化": BSONSerialise,
    "CBOR解码": CBORDecode,
    "CBOR编码": CBOREncode,
    "解析ObjectID时间戳": ParseObjectIDTimestamp,
};

export default OpModules;
