import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,symlink,mkdir,rename,realpath as fsRealpath,readdir as fsReaddir,lstat as fsLstat,open as fsOpen}from 'node:fs/promises';import {tmpdir}from 'node:os';import path from 'node:path';import {fileSnapshotMatches,humanFindingCode,manifestRelative,readHandleBounded,scanPlugin,safeRelative,maskSecrets,toMarkdown}from '../src/core/guard.mjs';
async function fixture(files={}){const root=await mkdtemp(path.join(tmpdir(),'guard-'));for(const [name,value] of Object.entries(files)){const p=path.join(root,name);await mkdir(path.dirname(p),{recursive:true});await writeFile(p,value)}return root}
test('rejects unsafe entrypoint paths and secret exposure',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'../oops',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],features:[{code:'bad',cmds:['files']}]}),'logo.svg':'x','preload.cjs':"const key='sk-abcdefghijklmnopqrstuvwxyz'"});const r=await scanPlugin(root);assert.ok(r.issues.some(x=>x.code==='entrypoint'));assert.ok(r.risks.some(x=>x.code==='secret'));assert.ok(!JSON.stringify(r).includes('abcdefghijklmnopqrstuvwxyz'));});
test('does not follow symlinks',async()=>{const root=await fixture({'plugin.json':'{}'});await symlink('/tmp',path.join(root,'out'));const r=await scanPlugin(root);assert.ok(r.issues.some(x=>x.code==='symlink'));});
test('path policy is platform-independent',()=>{assert.equal(safeRelative('../x'),false);assert.equal(safeRelative('C:\\x'),false);assert.equal(safeRelative('src/main.js'),true);assert.match(maskSecrets('token=abcdefghijklmnop'),/redacted/);});
test('win32 scanner paths use POSIX separators for manifest entrypoint comparison',()=>{const root='C:\\plugins\\plugin-guard',index=new Set(['src\\ui\\index.html','preload\\index.cjs','logo.svg'].map((relative)=>manifestRelative(root,path.win32.join(root,relative),path.win32)));assert.deepEqual([...index],['src/ui/index.html','preload/index.cjs','logo.svg']);assert.ok(index.has('src/ui/index.html'));assert.ok(index.has('preload/index.cjs'));});
test('final sanitizer covers prefixed, labeled, and complete or truncated private-key credentials',()=>{const values=[`github_pat_${'A'.repeat(24)}`,`ghp_${'B'.repeat(36)}`,`AKIA${'C'.repeat(16)}`,`AWS_SECRET_ACCESS_KEY=${'D'.repeat(40)}`,`Bearer ${'E'.repeat(24)}`],complete=`-----BEGIN PRIVATE KEY-----\n${'F'.repeat(64)}\n-----END PRIVATE KEY-----`,truncated=`-----BEGIN RSA PRIVATE KEY-----\n${'G'.repeat(64)}`;for(const value of [...values,complete,truncated]){const clean=maskSecrets(`before ${value} after`);assert.equal(clean.includes(value),false);assert.equal(clean.includes('BEGIN'),false);assert.match(clean,/redacted/);}});
test('human Markdown localizes labels without changing stable report values',()=>{const finding={level:'high',code:'feature-code',file:'[redacted].js',message:'Feature code 包含 [redacted]。'},report={scannedAt:'now',files:1,bytes:1,issues:[finding],risks:[]},value=toMarkdown(report);assert.match(value,/`高` `功能代码`/);assert.match(value,/功能代码 包含/);assert.match(value,/已脱敏/);assert.doesNotMatch(value,/`high`|feature-code|Feature code|\[redacted\]/);assert.deepEqual(finding,{level:'high',code:'feature-code',file:'[redacted].js',message:'Feature code 包含 [redacted]。'});assert.equal(maskSecrets('token=abcdefghijklmnop'),'[redacted]');});
test('every stable finding code has a deterministic Chinese human label',()=>{const expected={'dynamic-require':'动态依赖加载',eval:'动态代码执行','child-process':'子进程调用',shell:'命令解释器执行','whole-module-bridge':'整模块桥接暴露','remote-url':'远程网址','depth-limit':'目录深度超限','directory-race':'目录竞态风险',symlink:'符号链接','special-file':'特殊文件','case-collision':'路径大小写或 Unicode 冲突',manifest:'插件清单','manifest-field':'清单字段',entrypoint:'插件入口',categories:'分类配置',platform:'平台范围','feature-list':'功能列表','feature-code':'功能代码','feature-trigger':'功能触发器','manifest-json':'清单格式','manifest-read':'清单读取',containment:'路径越界','incomplete-file-read':'文件未完整读取','minified-preload':'预加载脚本可读性','relative-require-escape':'相对依赖越界','missing-relative-require':'相对依赖缺失','unknown-bridge':'未知桥接字段',secret:'疑似凭据','entry-invalidated':'入口已失效'};for(const [code,label] of Object.entries(expected))assert.equal(humanFindingCode(code),label);assert.equal(humanFindingCode('future-code'),'未分类检查项');});
test('fails closed for unknown preload bridge fields',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'bridge.readEverything = () => 1'});const r=await scanPlugin(root);assert.ok(r.risks.some(x=>x.code==='unknown-bridge'));});
test('only returns masked report fields and follows Node relative-require candidates',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'token=abcdefghijklmnop',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',categories:['other'],features:[{code:'safe'}]}), 'index.html':'ok','logo.svg':'x','preload.cjs':"require('./helper')",'helper.js':'module.exports=1','token=abcdefghijklmnop.js':'x'});const r=await scanPlugin(root);assert.ok(!JSON.stringify(r).includes('abcdefghijklmnop'));assert.equal(r.risks.some(x=>x.code==='missing-relative-require'),false);});
test('scans full audited text beyond the former snippet boundary',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',categories:['other'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'x'.repeat(100000)+'\neval(1)'});const r=await scanPlugin(root);assert.ok(r.risks.some(x=>x.code==='eval'));});
test('audited handle reads stop at the collected size plus one',async()=>{const fake=(value)=>{let cursor=0;return{async read(target,offset,length){const bytesRead=Math.min(length,value.length-cursor);if(bytesRead>0)value.copy(target,offset,cursor,cursor+bytesRead);cursor+=bytesRead;return{bytesRead}}}};assert.equal((await readHandleBounded(fake(Buffer.from('abc')),3)).toString(),'abc');await assert.rejects(readHandleBounded(fake(Buffer.from('abcd')),3),/增长后超过已授权大小/);});
test('audited file snapshots reject same-size identity or timestamp changes',()=>{const snapshot=(values={})=>({isFile:()=>true,dev:1,ino:2,size:3,mtimeMs:4,ctimeMs:5,...values});assert.equal(fileSnapshotMatches(snapshot(),snapshot()),true);assert.equal(fileSnapshotMatches(snapshot(),snapshot({ino:9})),false);assert.equal(fileSnapshotMatches(snapshot(),snapshot({ctimeMs:9})),false);});
test('drops a whole deep branch when its directory changes in place after readdir',async()=>{
  const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],categories:['other'],features:[]}),'index.html':'ok','logo.svg':'x','preload.cjs':'bridge.scan = () => 1','deep/inside.js':'inside-safe'});
  const canonicalRoot=await fsRealpath(root),deep=path.join(canonicalRoot,'deep'),late=path.join(deep,'late.js');
  let mutated=false,openedDeep=false;
  const r=await scanPlugin(root,{io:{
    readdir:async(directory,options)=>{
      const entries=await fsReaddir(directory,options);
      if(!mutated&&path.resolve(directory)===path.resolve(deep)){await writeFile(late,'eval(1)');mutated=true}
      return entries;
    },
    lstat:async(target)=>{
      const info=await fsLstat(target);
      if(!mutated||path.resolve(target)!==path.resolve(deep))return info;
      return new Proxy(info,{get(value,key){if(key==='mtimeMs'||key==='ctimeMs')return Number(value[key])+1000;const item=Reflect.get(value,key,value);return typeof item==='function'?item.bind(value):item}});
    },
    open:async(target,flags)=>{if(path.resolve(target).startsWith(`${path.resolve(deep)}${path.sep}`))openedDeep=true;return fsOpen(target,flags)}
  }});
  assert.equal(mutated,true);
  assert.equal(openedDeep,false);
  assert.ok(r.issues.some((finding)=>finding.code==='directory-race'&&finding.file==='deep'));
  assert.equal(r.entries.some((entry)=>entry.rel==='deep/inside.js'||entry.rel==='deep/late.js'),false);
  assert.equal(r.risks.some((finding)=>finding.file?.startsWith('deep/')),false);
  assert.equal(JSON.stringify(r).includes('late.js'),false);
});
test('drops every external entry when a deep directory is replaced before readdir',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],categories:['other'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'bridge.scan = () => 1','deep/inside.js':'inside'}),outside=await fixture({'outside-secret-marker.js':'eval(1)'}),canonicalRoot=await fsRealpath(root),deep=path.join(canonicalRoot,'deep'),backup=path.join(canonicalRoot,'deep-original');let swapped=false;const r=await scanPlugin(root,{io:{readdir:async(directory,options)=>{if(!swapped&&path.resolve(directory)===path.resolve(deep)){swapped=true;await rename(deep,backup);await symlink(outside,deep,process.platform==='win32'?'junction':'dir')}return fsReaddir(directory,options)}}});assert.equal(swapped,true);assert.ok(r.issues.some((finding)=>finding.code==='directory-race'));assert.equal(r.entries.some((entry)=>entry.rel.includes('outside-secret-marker')),false);assert.equal(r.risks.some((finding)=>finding.file?.includes('outside-secret-marker')),false);assert.equal(JSON.stringify(r).includes('outside-secret-marker'),false);});
test('does not read and does not retain a file opened through a replaced parent directory',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],categories:['other'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'bridge.scan = () => 1','deep/target.js':'inside-safe'}),outside=await fixture({'target.js':'outside-secret-marker'}),canonicalRoot=await fsRealpath(root),deep=path.join(canonicalRoot,'deep'),backup=path.join(canonicalRoot,'deep-original'),target=path.join(deep,'target.js');let swapped=false,readCalled=false;const r=await scanPlugin(root,{io:{open:async(file,flags)=>{if(!swapped&&path.resolve(file)===path.resolve(target)){swapped=true;await rename(deep,backup);await symlink(outside,deep,process.platform==='win32'?'junction':'dir')}const handle=await fsOpen(file,flags);if(path.resolve(file)!==path.resolve(target))return handle;return{stat:(...args)=>handle.stat(...args),read:(...args)=>{readCalled=true;return handle.read(...args)},close:()=>handle.close()}}}});assert.equal(swapped,true);assert.equal(readCalled,false);assert.ok(r.issues.some((finding)=>finding.code==='directory-race'));assert.equal(r.risks.some((finding)=>finding.file?.startsWith('deep/')),false);assert.equal(r.entries.some((entry)=>entry.rel==='deep/target.js'),false);assert.equal(JSON.stringify(r).includes('outside-secret-marker'),false);});
test('markdown report escapes untrusted file names and finding text',()=>{const value=toMarkdown({scannedAt:'now',files:1,bytes:1,issues:[{level:'high',code:'x`\n## forged',file:'bad`\n- injected.md',message:'line\n# fake'}],risks:[]});assert.ok(!value.includes('\n## forged'));assert.ok(!value.includes('\n- injected.md'));assert.ok(!value.includes('\n# fake'));});
test('default human scan retains 5,000 findings, preserves totals, and marks copied reports truncated',async()=>{const hits=5001,root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],categories:['other'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'bridge.unapproved = 1;\n'.repeat(hits)}),r=await scanPlugin(root);assert.equal(r.findingTotals.risks,hits);assert.equal(r.findingTotals.findings,hits);assert.equal(r.retainedFindings,5000);assert.equal(r.issues.length+r.risks.length,5000);assert.equal(r.findingsTruncated,true);const copied=toMarkdown(r);assert.match(copied,/已展示发现：5000 \/ 5001/);assert.match(copied,/证据已截断；汇总数量覆盖完整扫描结果。/);});
