import { parseHar, analyze, redact, diffReports, toMarkdown, humanizeRedactionMarkers } from '../core/analyze.js';
const $=s=>document.querySelector(s),out=$('#summary'),waterfall=$('#waterfall'),status=$('#status');let reports=[];
function el(tag,text,className){const x=document.createElement(tag);if(text!==undefined)x.textContent=String(text);if(className)x.className=className;return x;}
function render(){const report=reports[0];out.replaceChildren();waterfall.replaceChildren();if(!report)return;for(const [k,v]of [['请求数',report.entries],['总耗时',`${report.totalMs} ms`],['错误数',report.errors.length],['传输量',`${report.transferredBytes} B`]]){const card=el('article','', 'card');card.append(el('small',k),el('strong',v));out.append(card);}if(reports[1]){const labels={entries:'请求数',totalMs:'总耗时',transferredBytes:'传输量',errors:'错误数',slow:'慢请求数',duplicateBytes:'重复传输量'},delta=diffReports(report,reports[1]);out.append(el('article',`环境差异：${Object.entries(delta).map(([key,value])=>`${labels[key]||key} ${value>=0?'+':''}${value}`).join('；')}`,'card'));}const slow=report.slow.slice(0,16),longest=Math.max(1,...slow.map(item=>item.duration));if(!slow.length)waterfall.append(el('div','没有超过 1 秒的请求。','bar'));for(const item of slow){const row=el('div','', 'bar'),bar=el('i','');bar.style.setProperty('--fraction',String(Math.max(.02,item.duration/longest)));row.append(el('code',humanizeRedactionMarkers(`${item.status} ${item.method}`)),bar,el('span',`${Math.round(item.duration)} ms`),el('span',humanizeRedactionMarkers(item.url)));waterfall.append(row);}}
function setReports(texts){reports=texts.map(t=>analyze(parseHar(t)));render();}
$('#run').addEventListener('click',()=>{try{setReports([$('#input').value]);}catch(e){out.replaceChildren(el('p',e.message));waterfall.replaceChildren();}});
$('#choose').addEventListener('click',async()=>{try{await window.harDoctor?.choose?.();const files=window.harDoctor?.previewGranted?.();if(!files)throw Error('ZTools 桥接不可用');setReports(files);status.textContent='HAR 文件已载入并完成分析，可继续交给智能体分析'}catch(e){out.replaceChildren(el('p',e.message));}});
async function copyReport(text,label){try{if(window.harDoctor?.copyText)await window.harDoctor.copyText(text);else await navigator.clipboard.writeText(text);status.textContent=label}catch{status.textContent='当前环境无法复制'}}
$('#copy-md').addEventListener('click',()=>{if(reports[0])copyReport(humanizeRedactionMarkers(toMarkdown(reports[0],reports[1]&&diffReports(reports[0],reports[1]))),'已复制 Markdown 报告');});
$('#copy-json').addEventListener('click',()=>{if(reports[0])copyReport(JSON.stringify(redact(reports),null,2),'已复制 JSON 报告');});
