/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import Entropy from "../../operations/Entropy.mjs";
import HeatmapChart from "../../operations/HeatmapChart.mjs";
import HexDensityChart from "../../operations/HexDensityChart.mjs";
import ScatterChart from "../../operations/ScatterChart.mjs";
import SeriesChart from "../../operations/SeriesChart.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Charts = {
    "熵": Entropy,
    "热图": HeatmapChart,
    "六边形密度图": HexDensityChart,
    "散点图": ScatterChart,
    "折线图": SeriesChart,
};

export default OpModules;
