/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import A1Z26CipherDecode from "../../operations/A1Z26CipherDecode.mjs";
import A1Z26CipherEncode from "../../operations/A1Z26CipherEncode.mjs";
import AESDecrypt from "../../operations/AESDecrypt.mjs";
import AESEncrypt from "../../operations/AESEncrypt.mjs";
import AESKeyUnwrap from "../../operations/AESKeyUnwrap.mjs";
import AESKeyWrap from "../../operations/AESKeyWrap.mjs";
import AffineCipherDecode from "../../operations/AffineCipherDecode.mjs";
import AffineCipherEncode from "../../operations/AffineCipherEncode.mjs";
import AtbashCipher from "../../operations/AtbashCipher.mjs";
import BifidCipherDecode from "../../operations/BifidCipherDecode.mjs";
import BifidCipherEncode from "../../operations/BifidCipherEncode.mjs";
import BlowfishDecrypt from "../../operations/BlowfishDecrypt.mjs";
import BlowfishEncrypt from "../../operations/BlowfishEncrypt.mjs";
import CaesarBoxCipher from "../../operations/CaesarBoxCipher.mjs";
import CetaceanCipherDecode from "../../operations/CetaceanCipherDecode.mjs";
import CetaceanCipherEncode from "../../operations/CetaceanCipherEncode.mjs";
import ChaCha from "../../operations/ChaCha.mjs";
import DESDecrypt from "../../operations/DESDecrypt.mjs";
import DESEncrypt from "../../operations/DESEncrypt.mjs";
import DeriveEVPKey from "../../operations/DeriveEVPKey.mjs";
import DerivePBKDF2Key from "../../operations/DerivePBKDF2Key.mjs";
import ECDSASign from "../../operations/ECDSASign.mjs";
import ECDSASignatureConversion from "../../operations/ECDSASignatureConversion.mjs";
import ECDSAVerify from "../../operations/ECDSAVerify.mjs";
import GOSTDecrypt from "../../operations/GOSTDecrypt.mjs";
import GOSTEncrypt from "../../operations/GOSTEncrypt.mjs";
import GOSTKeyUnwrap from "../../operations/GOSTKeyUnwrap.mjs";
import GOSTKeyWrap from "../../operations/GOSTKeyWrap.mjs";
import GOSTSign from "../../operations/GOSTSign.mjs";
import GOSTVerify from "../../operations/GOSTVerify.mjs";
import GenerateECDSAKeyPair from "../../operations/GenerateECDSAKeyPair.mjs";
import GenerateRSAKeyPair from "../../operations/GenerateRSAKeyPair.mjs";
import PseudoRandomNumberGenerator from "../../operations/PseudoRandomNumberGenerator.mjs";
import RC2Decrypt from "../../operations/RC2Decrypt.mjs";
import RC2Encrypt from "../../operations/RC2Encrypt.mjs";
import RC4 from "../../operations/RC4.mjs";
import RC4Drop from "../../operations/RC4Drop.mjs";
import RSADecrypt from "../../operations/RSADecrypt.mjs";
import RSAEncrypt from "../../operations/RSAEncrypt.mjs";
import RSASign from "../../operations/RSASign.mjs";
import RSAVerify from "../../operations/RSAVerify.mjs";
import Rabbit from "../../operations/Rabbit.mjs";
import RailFenceCipherDecode from "../../operations/RailFenceCipherDecode.mjs";
import RailFenceCipherEncode from "../../operations/RailFenceCipherEncode.mjs";
import SM4Decrypt from "../../operations/SM4Decrypt.mjs";
import SM4Encrypt from "../../operations/SM4Encrypt.mjs";
import Salsa20 from "../../operations/Salsa20.mjs";
import TripleDESDecrypt from "../../operations/TripleDESDecrypt.mjs";
import TripleDESEncrypt from "../../operations/TripleDESEncrypt.mjs";
import VigenèreDecode from "../../operations/VigenèreDecode.mjs";
import VigenèreEncode from "../../operations/VigenèreEncode.mjs";
import XSalsa20 from "../../operations/XSalsa20.mjs";
import XXTEADecrypt from "../../operations/XXTEADecrypt.mjs";
import XXTEAEncrypt from "../../operations/XXTEAEncrypt.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Ciphers = {
    "A1Z26密码解密": A1Z26CipherDecode,
    "A1Z26密码加密": A1Z26CipherEncode,
    "AES解密": AESDecrypt,
    "AES加密": AESEncrypt,
    "AES密钥解包装": AESKeyUnwrap,
    "AES密钥包装": AESKeyWrap,
    "仿射密码解密": AffineCipherDecode,
    "仿射密码加密": AffineCipherEncode,
    "阿特巴希密码": AtbashCipher,
    "双密码解密": BifidCipherDecode,
    "双密码加密": BifidCipherEncode,
    "Blowfish解密": BlowfishDecrypt,
    "Blowfish加密": BlowfishEncrypt,
    "恺撒箱密码": CaesarBoxCipher,
    "鲸豚密码解密": CetaceanCipherDecode,
    "鲸豚密码加密": CetaceanCipherEncode,
    "ChaCha": ChaCha,
    "DES解密": DESDecrypt,
    "DES加密": DESEncrypt,
    "派生EVP密钥": DeriveEVPKey,
    "派生PBKDF2密钥": DerivePBKDF2Key,
    "ECDSA签名": ECDSASign,
    "ECDSA签名格式转换": ECDSASignatureConversion,
    "ECDSA验证": ECDSAVerify,
    "GOST解密": GOSTDecrypt,
    "GOST加密": GOSTEncrypt,
    "GOST密钥解包装": GOSTKeyUnwrap,
    "GOST密钥包装": GOSTKeyWrap,
    "GOST签名": GOSTSign,
    "GOST验证": GOSTVerify,
    "生成ECDSA密钥对": GenerateECDSAKeyPair,
    "生成RSA密钥对": GenerateRSAKeyPair,
    "伪随机数生成器": PseudoRandomNumberGenerator,
    "RC2解密": RC2Decrypt,
    "RC2加密": RC2Encrypt,
    "RC4": RC4,
    "RC4 Drop": RC4Drop,
    "RSA解密": RSADecrypt,
    "RSA加密": RSAEncrypt,
    "RSA签名": RSASign,
    "RSA验证": RSAVerify,
    "Rabbit": Rabbit,
    "篱笆密码解密": RailFenceCipherDecode,
    "篱笆密码加密": RailFenceCipherEncode,
    "SM4解密": SM4Decrypt,
    "SM4加密": SM4Encrypt,
    "Salsa20": Salsa20,
    "3DES解密": TripleDESDecrypt,
    "3DES加密": TripleDESEncrypt,
    "维吉尼亚密码解密": VigenèreDecode,
    "维吉尼亚密码加密": VigenèreEncode,
    "XSalsa20": XSalsa20,
    "XXTEA解密": XXTEADecrypt,
    "XXTEA加密": XXTEAEncrypt,
};

export default OpModules;
