/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2026
* @license Apache-2.0
*/
import AddTextToImage from "../../operations/AddTextToImage.mjs";
import BlurImage from "../../operations/BlurImage.mjs";
import ContainImage from "../../operations/ContainImage.mjs";
import ConvertImageFormat from "../../operations/ConvertImageFormat.mjs";
import CoverImage from "../../operations/CoverImage.mjs";
import CropImage from "../../operations/CropImage.mjs";
import DitherImage from "../../operations/DitherImage.mjs";
import ExtractEXIF from "../../operations/ExtractEXIF.mjs";
import ExtractLSB from "../../operations/ExtractLSB.mjs";
import ExtractRGBA from "../../operations/ExtractRGBA.mjs";
import FlipImage from "../../operations/FlipImage.mjs";
import GenerateImage from "../../operations/GenerateImage.mjs";
import GenerateQRCode from "../../operations/GenerateQRCode.mjs";
import ImageBrightnessContrast from "../../operations/ImageBrightnessContrast.mjs";
import ImageFilter from "../../operations/ImageFilter.mjs";
import ImageHueSaturationLightness from "../../operations/ImageHueSaturationLightness.mjs";
import ImageOpacity from "../../operations/ImageOpacity.mjs";
import InvertImage from "../../operations/InvertImage.mjs";
import NormaliseImage from "../../operations/NormaliseImage.mjs";
import ParseQRCode from "../../operations/ParseQRCode.mjs";
import RandomizeColourPalette from "../../operations/RandomizeColourPalette.mjs";
import RemoveEXIF from "../../operations/RemoveEXIF.mjs";
import RenderImage from "../../operations/RenderImage.mjs";
import ResizeImage from "../../operations/ResizeImage.mjs";
import RotateImage from "../../operations/RotateImage.mjs";
import SharpenImage from "../../operations/SharpenImage.mjs";
import SplitColourChannels from "../../operations/SplitColourChannels.mjs";
import ViewBitPlane from "../../operations/ViewBitPlane.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Image = {
    "图像加字": AddTextToImage,
    "模糊图像": BlurImage,
    "容纳图像": ContainImage,
    "图像格式转换": ConvertImageFormat,
    "覆盖图像": CoverImage,
    "裁剪图像": CropImage,
    "抖动图像": DitherImage,
    "提取EXIF": ExtractEXIF,
    "提取LSB": ExtractLSB,
    "提取RGBA": ExtractRGBA,
    "图像翻转": FlipImage,
    "生成图像": GenerateImage,
    "生成二维码": GenerateQRCode,
    "图像亮度/对比度": ImageBrightnessContrast,
    "图像滤镜": ImageFilter,
    "图像色调/饱和度/明度": ImageHueSaturationLightness,
    "图像透明度": ImageOpacity,
    "图像反色": InvertImage,
    "图像归一化": NormaliseImage,
    "解析二维码": ParseQRCode,
    "色板随机化": RandomizeColourPalette,
    "移除EXIF": RemoveEXIF,
    "渲染图像": RenderImage,
    "图像尺寸修改": ResizeImage,
    "旋转图像": RotateImage,
    "锐化图像": SharpenImage,
    "色彩通道分离": SplitColourChannels,
    "查看位平面": ViewBitPlane,
};

export default OpModules;
